export interface SubCategory {
  id: string;
  name: string;
  suggestedPriceDH: number; // Unit price in DH for multi, or total price for single
  timeEstimateHours: number;
  templateTitle?: string;
  templateDesc?: string;
  suggestedDeliverables?: string[];
  executionMode?: 'single' | 'multi' | 'both';
  recommendedPerformerCount?: number;
  minPriceDH?: number;
  marketAverageDH?: number;
  badge?: string;
  isUnusual?: boolean; // Unique / unconventional tasks people don't typically think of
  tag?: string; // e.g. 'mystery', 'calls', 'excel', 'telecom', 'queue', 'ecommerce'
}

export interface CategoryInfo {
  id: string;
  key: string;
  name: string;
  icon: string;
  color: string;
  accentBg: string;
  accentBorder: string;
  accentText: string;
  description: string;
  subcategories: SubCategory[];
}

export const TASK_CATEGORIES: CategoryInfo[] = [
  {
    id: 'micro',
    key: 'micro',
    name: 'Micro-tâches, Terrain & Mystère',
    icon: '⚡',
    color: 'amber',
    accentBg: 'bg-amber-50',
    accentBorder: 'border-amber-200',
    accentText: 'text-amber-800',
    description: 'Clients mystères, relevés de prix, files d’attente, tests sur téléphones et vérifications sur place.',
    subcategories: [
      {
        id: 'mystery-shopper',
        name: 'Client mystère : tester l’accueil d’un café ou boutique',
        suggestedPriceDH: 80,
        timeEstimateHours: 6,
        executionMode: 'single',
        minPriceDH: 50,
        marketAverageDH: 100,
        badge: '🕵️ Client Mystère',
        isUnusual: true,
        tag: 'mystery',
        templateTitle: 'Visite client mystère et évaluation de l’accueil / propreté',
        templateDesc: 'Se rendre dans l’établissement comme un client normal, commander un article, évaluer la politesse, la rapidité, l’hygiène et prendre une photo discrète du ticket.',
        suggestedDeliverables: [
          'Photo nette du ticket de caisse comme preuve de passage',
          'Grille d’évaluation remplie (Accueil, Temps d’attente, Propreté, Note globale /10)',
        ],
      },
      {
        id: 'supermarket-price-check',
        name: 'Relevé de prix d’un produit en rayon (Marjane / Carrefour / Bim)',
        suggestedPriceDH: 50,
        timeEstimateHours: 4,
        executionMode: 'single',
        minPriceDH: 30,
        marketAverageDH: 70,
        badge: '🛒 Relevé Prix',
        isUnusual: true,
        tag: 'mystery',
        templateTitle: 'Vérification du prix et disponibilité en rayon de 3 références',
        templateDesc: 'Se rendre dans un supermarché à proximité, localiser les produits demandés, photographier l’étiquette de prix en rayon et le code-barres.',
        suggestedDeliverables: [
          '3 photos nettes des étiquettes de prix en rayon avec date du jour',
          'Indication du magasin exact (Ville et quartier)',
        ],
      },
      {
        id: 'queue-reservation',
        name: 'Démarche administrative & Réservation de créneau en ligne',
        suggestedPriceDH: 100,
        timeEstimateHours: 4,
        executionMode: 'single',
        minPriceDH: 50,
        marketAverageDH: 120,
        badge: '🏛️ Démarche En Ligne',
        isUnusual: true,
        tag: 'admin',
        templateTitle: 'Prise de rendez-vous ou formalité administrative numérique',
        templateDesc: 'Assistance pour renseigner un formulaire en ligne, réserver un créneau horaire ou préparer un dossier administratif.',
        suggestedDeliverables: [
          'Capture d’écran ou confirmation PDF de la réservation / formalité effectuée',
          'Récapitulatif des pièces justificatives transmises',
        ],
      },
      {
        id: 'pharmacy-rare-medicine',
        name: 'Vérifier la disponibilité d’un médicament rare dans 5 pharmacies',
        suggestedPriceDH: 60,
        timeEstimateHours: 4,
        executionMode: 'single',
        minPriceDH: 40,
        marketAverageDH: 80,
        badge: '💊 Santé Urgente',
        isUnusual: true,
        tag: 'mystery',
        templateTitle: 'Tournée ou appel de 5 pharmacies pour localiser une boîte de médicament',
        templateDesc: 'Se renseigner auprès de 5 officines de garde ou du quartier pour savoir si le traitement recherché est disponible en stock.',
        suggestedDeliverables: [
          'Nom et adresse exacte de la pharmacie ayant le stock disponible',
          'Numéro de téléphone de la pharmacie et prix constaté',
        ],
      },
      {
        id: 'derb-ghallef-part-scout',
        name: 'Dénicher une pièce détachée ou composant rare à Derb Ghallef / Souk',
        suggestedPriceDH: 100,
        timeEstimateHours: 6,
        executionMode: 'single',
        minPriceDH: 70,
        marketAverageDH: 130,
        badge: '⚙️ Dénicheur',
        isUnusual: true,
        tag: 'mystery',
        templateTitle: 'Recherche physique d’une pièce spécifique au marché local',
        templateDesc: 'Faire le tour des boutiques spécialisées (Derb Ghallef, Garage Allal, Souk El Ghadir, etc.) pour trouver la référence exacte et obtenir le meilleur prix.',
        suggestedDeliverables: [
          'Photos de la pièce disponible chez le commerçant',
          'Coordonnées du vendeur et devis négocié',
        ],
      },
      {
        id: 'foot-traffic-counter',
        name: 'Compter le flux de piétons devant un local commercial (30 min)',
        suggestedPriceDH: 90,
        timeEstimateHours: 4,
        executionMode: 'single',
        minPriceDH: 60,
        marketAverageDH: 120,
        badge: '🚶 Étude Flux',
        isUnusual: true,
        tag: 'mystery',
        templateTitle: 'Comptage de passage piétons et véhicules pour étude d’implantation',
        templateDesc: 'S’installer devant l’adresse indiquée pendant 30 minutes (aux heures de pointe) et compter le nombre de personnes passant devant la vitrine.',
        suggestedDeliverables: [
          'Tableau avec nombre exact de passants (Hommes, Femmes, Véhicules)',
          'Photo panoramique de la rue prise au début et à la fin',
        ],
      },
      {
        id: 'google-maps-reviews',
        name: 'Avis Google Maps vérifié (Comptes marocains actifs)',
        suggestedPriceDH: 15,
        timeEstimateHours: 6,
        executionMode: 'multi',
        recommendedPerformerCount: 10,
        minPriceDH: 10,
        marketAverageDH: 20,
        badge: '🔥 Populaire',
        isUnusual: false,
        tag: 'reviews',
        templateTitle: 'Rédaction d’un avis Google Maps 5 étoiles authentique',
        templateDesc: 'Poster un avis détaillé et positif avec compte Google actif au Maroc. Mentionner la qualité de service et joindre une capture d’écran de validation.',
        suggestedDeliverables: [
          'Capture d’écran de l’avis publié avec le profil visible',
          'Lien direct ou confirmation du nom du compte ayant posté',
        ],
      },
      {
        id: 'android-samsung-test',
        name: 'Test d’application mobile sur Android / Samsung',
        suggestedPriceDH: 25,
        timeEstimateHours: 4,
        executionMode: 'multi',
        recommendedPerformerCount: 5,
        minPriceDH: 15,
        marketAverageDH: 30,
        badge: '⚡ Express',
        isUnusual: false,
        tag: 'telecom',
        templateTitle: 'Test d’installation et parcours d’achat sur Android / Samsung',
        templateDesc: 'Installer l’application Android sur réseau Maroc Telecom / Inwi / Orange, tester l’inscription OTP et vérifier qu’aucun crash n’apparaît.',
        suggestedDeliverables: [
          '3 captures d’écran des étapes clés (accueil, inscription, profil)',
          'Modèle exact du smartphone et version Android testée',
          'Rapport bref des bugs ou lenteurs éventuelles',
        ],
      },
      {
        id: 'ios-iphone-test',
        name: 'Test d’application mobile sur iPhone / iOS',
        suggestedPriceDH: 30,
        timeEstimateHours: 4,
        executionMode: 'multi',
        recommendedPerformerCount: 5,
        minPriceDH: 20,
        marketAverageDH: 35,
        badge: '📱 iOS',
        isUnusual: false,
        tag: 'telecom',
        templateTitle: 'Test d’ergonomie et fluidité sur iPhone (iOS 16+)',
        templateDesc: 'Tester l’affichage responsive sur Safari mobile et tester le formulaire de commande avec captures d’écran.',
        suggestedDeliverables: [
          'Captures d’écran sur Safari iOS',
          'Indication du modèle d’iPhone utilisé',
        ],
      },
      {
        id: 'admin-errands',
        name: 'Démarches & Dépôt de documents urgents en ville',
        suggestedPriceDH: 120,
        timeEstimateHours: 6,
        executionMode: 'single',
        minPriceDH: 80,
        marketAverageDH: 140,
        badge: '🏛️ Terrain',
        isUnusual: false,
        tag: 'errands',
        templateTitle: 'Dépôt d’un pli ou document urgent au bureau d’ordre',
        templateDesc: 'Récupération d’un pli fermé et dépôt physique avec obtention d’un récépissé officiel tamponné et daté.',
        suggestedDeliverables: [
          'Photo nette du récépissé avec cachet officiel et date',
          'Confirmation immédiate par WhatsApp ou chat',
        ],
      },
      {
        id: 'site-visit-inspection',
        name: 'Visite de contrôle & Photos sur place',
        suggestedPriceDH: 150,
        timeEstimateHours: 12,
        executionMode: 'single',
        minPriceDH: 100,
        marketAverageDH: 180,
        badge: '📸 Terrain',
        isUnusual: false,
        tag: 'errands',
        templateTitle: 'Vérification sur place et reportage photo d’un bien / local commercial',
        templateDesc: 'Déplacement physique à l’adresse indiquée pour prendre 10 photos géolocalisées et noter l’état des lieux.',
        suggestedDeliverables: [
          'Album de 10 photos nettes géolocalisées et datées',
          'Compte-rendu succinct de visite',
        ],
      },
    ],
  },
  {
    id: 'assistance',
    key: 'assistance',
    name: 'Saisie, Appels & Négociation',
    icon: '📊',
    color: 'amber',
    accentBg: 'bg-amber-50',
    accentBorder: 'border-amber-200',
    accentText: 'text-amber-700',
    description: 'Appels anonymes concurrents, patience hotline, nettoyage Excel, saisie de tickets froissés.',
    subcategories: [
      {
        id: 'competitor-price-call',
        name: 'Appel anonyme chez un concurrent pour obtenir sa grille tarifaire',
        suggestedPriceDH: 50,
        timeEstimateHours: 4,
        executionMode: 'single',
        minPriceDH: 35,
        marketAverageDH: 70,
        badge: '🕵️ Benchmark Prix',
        isUnusual: true,
        tag: 'calls',
        templateTitle: 'Appel mystère en Darija pour demander devis et prix à un concurrent',
        templateDesc: 'Appeler un concurrent en se faisant passer pour un client intéressé, poser les questions clés sur ses tarifs, délais et remises, et noter toutes les réponses.',
        suggestedDeliverables: [
          'Compte-rendu avec tarifs exacts, remises proposées et conditions de vente',
          'Heure de l’appel et nom de l’interlocuteur',
        ],
      },
      {
        id: 'wait-on-hotline',
        name: 'Patienter au téléphone sur une hotline / SAV jusqu’à avoir un agent',
        suggestedPriceDH: 50,
        timeEstimateHours: 2,
        executionMode: 'single',
        minPriceDH: 30,
        marketAverageDH: 70,
        badge: '⏳ Patience SAV',
        isUnusual: true,
        tag: 'calls',
        templateTitle: 'Attente sur répondeur téléphonique et mise en relation directe',
        templateDesc: 'Appeler un numéro surtaxé ou un standard saturé (banque, opérateur, compagnie), patienter le temps nécessaire et transférer ou alerter dès qu’un conseiller décroche.',
        suggestedDeliverables: [
          'Alerte immédiate par message/appel dès que l’agent humain répond',
          'Capture d’écran de la durée d’appel',
        ],
      },
      {
        id: 'receipts-to-excel',
        name: 'Reconstituer un tableau Excel à partir de photos de tickets froissés',
        suggestedPriceDH: 80,
        timeEstimateHours: 12,
        executionMode: 'single',
        minPriceDH: 50,
        marketAverageDH: 110,
        badge: '🧾 Tickets Froissés',
        isUnusual: true,
        tag: 'excel',
        templateTitle: 'Saisie de 30 reçus et tickets de caisse scannés en tableau Excel',
        templateDesc: 'Déchiffrer 30 photos de tickets de caisse parfois froissés ou peu lisibles, et reporter les dates, magasins, montants HT et TTC dans un tableau bien classé.',
        suggestedDeliverables: [
          'Fichier Excel (.xlsx) propre avec totaux automatiques vérifiés',
          'Signalement des tickets illisibles s’il y en a',
        ],
      },
      {
        id: 'clean-excel-duplicates',
        name: 'Nettoyer un fichier Excel de 1000 contacts (Doublons & faux numéros)',
        suggestedPriceDH: 90,
        timeEstimateHours: 12,
        executionMode: 'single',
        minPriceDH: 60,
        marketAverageDH: 130,
        badge: '🧹 Nettoyage Données',
        isUnusual: true,
        tag: 'excel',
        templateTitle: 'Nettoyage et standardisation des numéros marocains (+212) sous Excel',
        templateDesc: 'Supprimer les lignes en double, corriger les espaces dans les numéros, ajouter le préfixe marocain normalisé (+212 6... / +212 7...) et vérifier les emails invalides.',
        suggestedDeliverables: [
          'Fichier Excel nettoyé sans aucun doublon',
          'Rapport bref du nombre de lignes supprimées et corrigées',
        ],
      },
      {
        id: 'bank-statement-pdf-to-excel',
        name: 'Convertir un relevé bancaire PDF scanné en Excel (Débit/Crédit)',
        suggestedPriceDH: 70,
        timeEstimateHours: 6,
        executionMode: 'single',
        minPriceDH: 45,
        marketAverageDH: 90,
        badge: '🏦 Relevé Bancaire',
        isUnusual: true,
        tag: 'excel',
        templateTitle: 'Reconstitution exacte d’un relevé bancaire scanné dans un tableur',
        templateDesc: 'Recopier ligne par ligne les opérations bancaires d’un PDF non copiable avec date d’opération, libellé, débit, crédit et solde vérifié.',
        suggestedDeliverables: [
          'Tableau Excel avec formule de contrôle de solde équilibrée à 100%',
        ],
      },
      {
        id: 'handwritten-notes-transcription',
        name: 'Déchiffrer et saisir des notes manuscrites scannées en Word propre',
        suggestedPriceDH: 70,
        timeEstimateHours: 12,
        executionMode: 'single',
        minPriceDH: 45,
        marketAverageDH: 95,
        badge: '✍️ Décryptage',
        isUnusual: true,
        tag: 'excel',
        templateTitle: 'Retranscription soignée de notes prises à la main',
        templateDesc: 'Relire 10 pages de notes de réunion manuscrites écrites au stylo et les transformer en compte-rendu clair et mis en page dans Microsoft Word.',
        suggestedDeliverables: [
          'Fichier Word modifiable avec titres et puces structurées',
        ],
      },
      {
        id: 'supplier-call',
        name: 'Appel téléphonique de 5 commerçants / grossistes en Darija',
        suggestedPriceDH: 100,
        timeEstimateHours: 4,
        executionMode: 'single',
        minPriceDH: 70,
        marketAverageDH: 130,
        badge: '📞 Express',
        isUnusual: false,
        tag: 'calls',
        templateTitle: 'Vérification de stock et négociation de prix par téléphone',
        templateDesc: 'Contacter 5 boutiques ou grossistes (Derb Ghallef, Garage Allal...), vérifier la disponibilité des articles en Darija et noter les prix.',
        suggestedDeliverables: [
          'Tableau avec réponses précises, noms des interlocuteurs et prix constatés',
        ],
      },
      {
        id: 'web-research-leads',
        name: 'Collecte de 50 contacts d’entreprises ciblées au Maroc',
        suggestedPriceDH: 150,
        timeEstimateHours: 24,
        executionMode: 'single',
        minPriceDH: 100,
        marketAverageDH: 180,
        templateTitle: 'Recherche web et enrichissement d’une base de données B2B',
        templateDesc: 'Collecter 50 entreprises selon vos critères (Secteur, Ville, Nom du gérant, Téléphone, Email, Site web).',
        suggestedDeliverables: [
          'Fichier Excel contenant les 50 contacts qualifiés et vérifiés',
        ],
      },
    ],
  },
  {
    id: 'development',
    key: 'development',
    name: 'Web, Tests Réseau & E-commerce',
    icon: '💻',
    color: 'blue',
    accentBg: 'bg-blue-50',
    accentBorder: 'border-blue-200',
    accentText: 'text-blue-700',
    description: 'Test réception SMS OTP opérateurs, téléchargement gros fichiers fibre, test panier COD.',
    subcategories: [
      {
        id: 'test-sms-otp-networks',
        name: 'Tester la réception de SMS OTP sur les 3 réseaux (IAM, Inwi, Orange)',
        suggestedPriceDH: 20,
        timeEstimateHours: 4,
        executionMode: 'multi',
        recommendedPerformerCount: 6,
        minPriceDH: 12,
        marketAverageDH: 25,
        badge: '📶 Test Opérateurs',
        isUnusual: true,
        tag: 'telecom',
        templateTitle: 'Test de délivrabilité d’un code SMS OTP sur puces marocaines',
        templateDesc: 'Saisir son numéro sur le formulaire web, chronométrer le temps de réception du code SMS et vérifier qu’il n’est pas filtré comme spam.',
        suggestedDeliverables: [
          'Capture d’écran du SMS reçu avec horodatage visible',
          'Nom de l’opérateur utilisé (Maroc Telecom, Inwi ou Orange)',
          'Temps mesuré en secondes avant réception',
        ],
      },
      {
        id: 'heavy-file-download-fiber',
        name: 'Télécharger un gros fichier (20 Go) sur connexion Fibre et l’uploader',
        suggestedPriceDH: 50,
        timeEstimateHours: 4,
        executionMode: 'single',
        minPriceDH: 30,
        marketAverageDH: 70,
        badge: '⚡ Fibre Express',
        isUnusual: true,
        tag: 'telecom',
        templateTitle: 'Dépannage connexion lente : téléchargement rapide et transfert Cloud',
        templateDesc: 'Utiliser une connexion fibre optique très haut débit pour télécharger des archives volumineuses et les transférer sur Google Drive ou Mega.',
        suggestedDeliverables: [
          'Lien direct Google Drive avec le fichier intégralement transféré',
          'Vérification de la somme de contrôle ou taille du fichier',
        ],
      },
      {
        id: 'test-cod-checkout-speed',
        name: 'Tester le formulaire COD d’un site concurrent et chronométrer l’appel',
        suggestedPriceDH: 35,
        timeEstimateHours: 4,
        executionMode: 'single',
        minPriceDH: 20,
        marketAverageDH: 50,
        badge: '📦 Test COD',
        isUnusual: true,
        tag: 'ecommerce',
        templateTitle: 'Passer une commande test et mesurer le temps de confirmation téléphonique',
        templateDesc: 'Commander un article fictif sur une boutique e-commerce marocaine, noter si le panier est fluide, et enregistrer le délai avant le rappel de confirmation.',
        suggestedDeliverables: [
          'Captures du parcours d’achat',
          'Délai exact en minutes avant le coup de fil de confirmation',
          'Note sur le discours commercial de l’opératrice',
        ],
      },
      {
        id: 'smart-tv-console-test',
        name: 'Tester l’affichage d’un site web sur écran Smart TV ou console de jeu',
        suggestedPriceDH: 40,
        timeEstimateHours: 4,
        executionMode: 'single',
        minPriceDH: 25,
        marketAverageDH: 60,
        badge: '📺 Test Smart TV',
        isUnusual: true,
        tag: 'telecom',
        templateTitle: 'Test de compatibilité sur navigateur de télévision connectée',
        templateDesc: 'Ouvrir l’URL sur une Smart TV (Samsung Tizen, LG WebOS, Android TV) ou PlayStation/Xbox et vérifier la lisibilité des textes avec photos.',
        suggestedDeliverables: [
          '2 photos nettes de l’écran de télévision affichant le site',
          'Remarques sur la navigabilité à la télécommande',
        ],
      },
      {
        id: 'shopify-woocommerce',
        name: 'Paramétrage boutique Shopify / WooCommerce complète',
        suggestedPriceDH: 350,
        timeEstimateHours: 48,
        executionMode: 'single',
        minPriceDH: 250,
        marketAverageDH: 450,
        badge: '🛍️ E-commerce & Web',
        isUnusual: false,
        tag: 'ecommerce',
        templateTitle: 'Configuration complète d’une boutique e-commerce Shopify / WooCommerce',
        templateDesc: 'Installation du thème, configuration du tunnel de commande express, intégration des transporteurs et 10 fiches produits soignées.',
        suggestedDeliverables: [
          'Boutique 100% fonctionnelle testée avec commande témoin',
          'Tunnel d’achat fluide et responsive mobile',
        ],
      },
      {
        id: 'bug-fix',
        name: 'Correction d’un bug CSS / JavaScript / WordPress',
        suggestedPriceDH: 150,
        timeEstimateHours: 6,
        executionMode: 'single',
        minPriceDH: 80,
        marketAverageDH: 200,
        badge: '⚡ Urgent',
        isUnusual: false,
        tag: 'telecom',
        templateTitle: 'Résolution rapide d’un bug d’affichage ou d’erreur sur site',
        templateDesc: 'Diagnostic et correction d’un dysfonctionnement ciblé survenu sur votre site internet.',
        suggestedDeliverables: [
          'Code corrigé et vérifié sur Chrome, Safari et mobile',
          'Explication brève de la cause et solution appliquée',
        ],
      },
    ],
  },
  {
    id: 'marketing',
    key: 'marketing',
    name: 'Marketing, Réputation & Veille',
    icon: '📱',
    color: 'rose',
    accentBg: 'bg-rose-50',
    accentBorder: 'border-rose-200',
    accentText: 'text-rose-700',
    description: 'Signalement de faux comptes imposteurs, veille pubs concurrents, voix off accents régionaux.',
    subcategories: [
      {
        id: 'report-imposter-account',
        name: 'Signaler en masse un faux profil / compte usurpateur sur Instagram',
        suggestedPriceDH: 10,
        timeEstimateHours: 4,
        executionMode: 'multi',
        recommendedPerformerCount: 20,
        minPriceDH: 6,
        marketAverageDH: 15,
        badge: '🛡️ Anti-Imposteur',
        isUnusual: true,
        tag: 'reputation',
        templateTitle: 'Signalement collectif d’un profil imposteur usurpant notre identité',
        templateDesc: 'Signaler le faux compte sur Instagram/Facebook pour usurpation d’identité ou arnaque afin d’accélérer son bannissement par les modérateurs.',
        suggestedDeliverables: [
          'Capture d’écran de la confirmation de signalement envoyé à Meta',
        ],
      },
      {
        id: 'competitor-ads-spy',
        name: 'Prendre 5 captures des publicités Meta Ads actives d’un concurrent',
        suggestedPriceDH: 40,
        timeEstimateHours: 4,
        executionMode: 'single',
        minPriceDH: 25,
        marketAverageDH: 60,
        badge: '📱 Espionnage Pubs',
        isUnusual: true,
        tag: 'reputation',
        templateTitle: 'Veille publicitaire Facebook / Instagram Ads sur un concurrent',
        templateDesc: 'Fouiller la bibliothèque publicitaire Meta, enregistrer les 5 annonces actives d’un concurrent avec textes d’accroche et offres promotionnelles.',
        suggestedDeliverables: [
          'Dossier de captures d’écran des visuels et copies des textes publicitaires',
          'Date de début de diffusion de chaque campagne',
        ],
      },
      {
        id: 'regional-accent-voiceover',
        name: 'Voix off en Darija avec accent régional (Chamali, Fassi, Marrakchi)',
        suggestedPriceDH: 140,
        timeEstimateHours: 12,
        executionMode: 'single',
        minPriceDH: 90,
        marketAverageDH: 180,
        badge: '🗣️ Accent Régional',
        isUnusual: true,
        tag: 'audio',
        templateTitle: 'Enregistrement voix off en Darija avec intonation locale authentique',
        templateDesc: 'Lecture vivante d’un script publicitaire de 45 secondes avec un accent naturel du Nord (Tanger/Tétouan), de Fès ou de Marrakech.',
        suggestedDeliverables: [
          'Fichier audio MP3 / WAV propre sans bruit de fond',
          'Deux versions d’intonations différentes fournies',
        ],
      },
      {
        id: 'find-niche-micro-influencers',
        name: 'Dénicher 10 micro-influenceurs marocains de niche avec numéros',
        suggestedPriceDH: 110,
        timeEstimateHours: 12,
        executionMode: 'single',
        minPriceDH: 70,
        marketAverageDH: 150,
        badge: '🎯 Influenceurs Niche',
        isUnusual: true,
        tag: 'reputation',
        templateTitle: 'Recherche de 10 créateurs marocains engagés (5k à 30k abonnés)',
        templateDesc: 'Trouver 10 profils Instagram / TikTok pertinents dans une thématique précise (ex: mamans, cuisine marocaine, tech) avec coordonnées de contact direct.',
        suggestedDeliverables: [
          'Tableau Excel avec liens des profils, taux d’engagement approximatif et WhatsApp/Email',
        ],
      },
      {
        id: 'reels-tiktok-editing',
        name: 'Montage dynamique de 3 vidéos TikTok / Reels',
        suggestedPriceDH: 180,
        timeEstimateHours: 24,
        executionMode: 'single',
        minPriceDH: 100,
        marketAverageDH: 220,
        badge: '🎬 Populaire',
        isUnusual: false,
        tag: 'video',
        templateTitle: 'Montage court et rythmé de 3 vidéos verticales (Reels/TikTok)',
        templateDesc: 'Découpage des rushs, ajout de sous-titres animés captivants, sons tendance et zooms dynamiques.',
        suggestedDeliverables: [
          '3 fichiers vidéo MP4 verticaux (1080x1920) haute qualité',
          'Sous-titres synchronisés et musique libre de droits',
        ],
      },
    ],
  },
  {
    id: 'copywriting',
    key: 'copywriting',
    name: 'Traduction, Démarches & Écritures',
    icon: '✍️',
    color: 'emerald',
    accentBg: 'bg-emerald-50',
    accentBorder: 'border-emerald-200',
    accentText: 'text-emerald-700',
    description: 'Aide démarches portails publics, lettres de litige syndic, sous-titres Darija Arabizi.',
    subcategories: [
      {
        id: 'online-public-portal-help',
        name: 'Assistance pour remplir une demande en ligne sur portail public (CNSS, Massar, RDV)',
        suggestedPriceDH: 60,
        timeEstimateHours: 4,
        executionMode: 'single',
        minPriceDH: 40,
        marketAverageDH: 80,
        badge: '💻 Dépannage Portail',
        isUnusual: true,
        tag: 'legal',
        templateTitle: 'Aide pas-à-pas pour formalité administrative sur internet',
        templateDesc: 'Guider par appel ou message pour remplir sans erreur un formulaire administratif officiel (téléchargement des pièces requises et validation du dossier).',
        suggestedDeliverables: [
          'Récépissé de confirmation de la demande téléchargé en PDF',
        ],
      },
      {
        id: 'formal-dispute-letter',
        name: 'Rédiger une lettre de réclamation formelle pour litige (Syndic, Propriétaire, Voisinage)',
        suggestedPriceDH: 80,
        timeEstimateHours: 12,
        executionMode: 'single',
        minPriceDH: 50,
        marketAverageDH: 110,
        badge: '⚖️ Lettre Litige',
        isUnusual: true,
        tag: 'legal',
        templateTitle: 'Rédaction d’une lettre de mise en demeure amiable et polie',
        templateDesc: 'Rédiger une lettre ferme et bien formulée rappelant les faits et obligations légales pour régler un problème de copropriété, fuite d’eau ou caution non restituée.',
        suggestedDeliverables: [
          'Lettre rédigée en Word et PDF prête à être signée et envoyée avec accusé',
        ],
      },
      {
        id: 'subtitles-darija-arabizi',
        name: 'Sous-titrer une vidéo en Darija (Arabizi ou Alphabet Arabe)',
        suggestedPriceDH: 80,
        timeEstimateHours: 12,
        executionMode: 'single',
        minPriceDH: 50,
        marketAverageDH: 110,
        badge: '🎬 Sous-titres Darija',
        isUnusual: true,
        tag: 'translation',
        templateTitle: 'Transcription et sous-titrage synchronisé de propos oraux en Darija',
        templateDesc: 'Écouter une vidéo parlée en Darija marocaine et créer un fichier de sous-titres (.srt ou incrusté) écrit en arabe ou en 3aransiya.',
        suggestedDeliverables: [
          'Fichier .srt synchronisé ou vidéo avec sous-titres incrustés lisibles',
        ],
      },
      {
        id: 'find-cheapest-flight-hacks',
        name: 'Rechercher la meilleure combinaison de vols et dates flexibles',
        suggestedPriceDH: 70,
        timeEstimateHours: 6,
        executionMode: 'single',
        minPriceDH: 45,
        marketAverageDH: 90,
        badge: '✈️ Astuce Billets',
        isUnusual: true,
        tag: 'travel',
        templateTitle: 'Comparatif d’itinéraires malins pour économiser sur un voyage au départ du Maroc',
        templateDesc: 'Tester les aéroports voisins, escales intelligentes et compagnies low-cost pour dénicher le tarif le plus bas possible selon vos dates.',
        suggestedDeliverables: [
          'Rapport avec 3 options détaillées (prix, compagnies, escales et liens directs)',
        ],
      },
      {
        id: 'translation-ar-fr',
        name: 'Traduction Arabe ⇄ Français (Document 2-3 pages)',
        suggestedPriceDH: 120,
        timeEstimateHours: 24,
        executionMode: 'single',
        minPriceDH: 80,
        marketAverageDH: 150,
        badge: '🌟 Populaire',
        isUnusual: false,
        tag: 'translation',
        templateTitle: 'Traduction fidèle de document (Arabe vers Français)',
        templateDesc: 'Traduction soignée d’un document de 2 à 3 pages. Vocabulaire précis et sans fautes.',
        suggestedDeliverables: [
          'Fichier Word modifiable + version PDF propre',
        ],
      },
    ],
  },
  {
    id: 'design',
    key: 'design',
    name: 'Graphisme, Retouches & Visuels',
    icon: '🎨',
    color: 'purple',
    accentBg: 'bg-purple-50',
    accentBorder: 'border-purple-200',
    accentText: 'text-purple-700',
    description: 'Retouches photo express, détourage produits, visuels réseaux sociaux et logos.',
    subcategories: [
      {
        id: 'photo-remove-stranger',
        name: 'Effacer un passant ou objet gênant en arrière-plan d’une photo',
        suggestedPriceDH: 40,
        timeEstimateHours: 4,
        executionMode: 'single',
        minPriceDH: 25,
        marketAverageDH: 60,
        badge: '🪄 Retouche Magique',
        isUnusual: true,
        tag: 'design',
        templateTitle: 'Suppression nette d’éléments indésirables sur photo personnelle ou produit',
        templateDesc: 'Retirer des personnes en arrière-plan, câbles électriques ou taches tout en reconstruisant le décor naturellement.',
        suggestedDeliverables: [
          'Photo retouchée en haute définition originale sans perte de qualité',
        ],
      },
      {
        id: 'photo-editing',
        name: 'Retouche & Détourage de 20 photos produits',
        suggestedPriceDH: 100,
        timeEstimateHours: 12,
        executionMode: 'single',
        minPriceDH: 60,
        marketAverageDH: 130,
        badge: '📸 E-commerce',
        isUnusual: false,
        tag: 'design',
        templateTitle: 'Détourage propre sur fond blanc / transparent de 20 photos',
        templateDesc: 'Suppression parfaite de l’arrière-plan, ombrage naturel et recadrage aux dimensions standard du commerce en ligne.',
        suggestedDeliverables: [
          '20 images PNG fond transparent haute qualité',
          '20 images JPG fond blanc optimisées pour le web',
        ],
      },
      {
        id: 'logo-branding',
        name: 'Logo professionnel & Identité visuelle (3 pistes)',
        suggestedPriceDH: 300,
        timeEstimateHours: 48,
        executionMode: 'single',
        minPriceDH: 150,
        marketAverageDH: 350,
        badge: '💎 Best-seller',
        isUnusual: false,
        tag: 'design',
        templateTitle: 'Création d’un logo moderne vectoriel (3 propositions originales)',
        templateDesc: 'Conception d’un logo unique et épuré. Fourniture des déclinaisons couleurs, fond blanc et fond transparent.',
        suggestedDeliverables: [
          'Fichiers vectoriels éditables (AI, EPS, SVG)',
          'Exports haute définition (PNG transparent, JPG 300 DPI, PDF)',
        ],
      },
      {
        id: 'social-media-posts',
        name: 'Pack de 5 visuels pour Instagram / Facebook',
        suggestedPriceDH: 200,
        timeEstimateHours: 24,
        executionMode: 'single',
        minPriceDH: 120,
        marketAverageDH: 250,
        badge: '🔥 Tendance',
        isUnusual: false,
        tag: 'design',
        templateTitle: 'Conception graphique de 5 publications réseaux sociaux percutantes',
        templateDesc: 'Création de 5 visuels adaptés à votre charte graphique pour promouvoir vos offres ou votre marque.',
        suggestedDeliverables: [
          '5 visuels HD au format carré (1:1) et vertical Story (9:16)',
          'Lien du template Canva éditable ou source PSD',
        ],
      },
    ],
  },
];

export const MOROCCAN_CITIES = [
  'Casablanca',
  'Rabat',
  'Marrakech',
  'Tanger',
  'Fès',
  'Agadir',
  'Salé',
  'Meknès',
  'Oujda',
  'Kénitra',
  'Tétouan',
  'Mohammédia',
  'El Jadida',
  'Nador',
  'Béni Mellal',
  'Autre ville au Maroc',
];

/**
 * Flattens all subcategories across categories with their parent category metadata.
 */
export interface FlatTaskSuggestion extends SubCategory {
  categoryKey: string;
  categoryName: string;
  categoryIcon: string;
}

export function getAllTaskSuggestions(): FlatTaskSuggestion[] {
  const result: FlatTaskSuggestion[] = [];
  for (const cat of TASK_CATEGORIES) {
    for (const sub of cat.subcategories) {
      result.push({
        ...sub,
        categoryKey: cat.key,
        categoryName: cat.name,
        categoryIcon: cat.icon,
      });
    }
  }
  return result;
}
