export interface SubCategory {
  id: string;
  name: string;
  suggestedPriceDH: number;
  timeEstimateHours: number;
  templateTitle?: string;
  templateDesc?: string;
  suggestedDeliverables?: string[];
}

export interface CategoryInfo {
  id: string;
  key: string;
  name: string;
  icon: string;
  color: string;
  accentBg: string;
  accentBorder: string;
  accentText: string;
  description: string;
  subcategories: SubCategory[];
}

export const TASK_CATEGORIES: CategoryInfo[] = [
  {
    id: 'copywriting',
    key: 'copywriting',
    name: 'Traduction & Rédaction',
    icon: '✍️',
    color: 'emerald',
    accentBg: 'bg-emerald-50',
    accentBorder: 'border-emerald-200',
    accentText: 'text-emerald-700',
    description: 'Traductions assermentées ou courantes, rédaction web, fiches produits, mémoires et corrections.',
    subcategories: [
      {
        id: 'translation-ar-fr',
        name: 'Traduction Arabe ⇄ Français / Anglais',
        suggestedPriceDH: 120,
        timeEstimateHours: 24,
        templateTitle: 'Traduction de document (Arabe vers Français)',
        templateDesc: 'Traduction fidèle et soignée d’un document de 2 à 3 pages. Vocabulaire précis et sans fautes.',
        suggestedDeliverables: ['Document traduit au format Word / PDF', 'Relecture finale sans fautes'],
      },
      {
        id: 'copywriting-articles',
        name: 'Rédaction d’articles & Contenu web',
        suggestedPriceDH: 150,
        timeEstimateHours: 24,
        templateTitle: 'Rédaction d’un article de blog optimisé SEO (800 mots)',
        templateDesc: 'Rédaction d’un article informatif, bien structuré avec titres et sous-titres, adapté au public cible.',
        suggestedDeliverables: ['Fichier Word ou Google Doc avec titres H1/H2', 'Méta-description et mots-clés'],
      },
      {
        id: 'ecommerce-descriptions',
        name: 'Fiches produits e-commerce',
        suggestedPriceDH: 100,
        timeEstimateHours: 24,
        templateTitle: 'Rédaction de 10 fiches produits pour boutique en ligne',
        templateDesc: 'Descriptions attractives et vendeuses pour 10 articles (titre, caractéristiques, arguments de vente).',
        suggestedDeliverables: ['Tableau Excel ou fichier Word structuré', 'Points forts et descriptions courtes'],
      },
      {
        id: 'audio-transcription',
        name: 'Transcription audio / vidéo en texte',
        suggestedPriceDH: 80,
        timeEstimateHours: 12,
        templateTitle: 'Transcription complète d’un audio de 30 minutes',
        templateDesc: 'Retranscription fidèle par écrit d’un enregistrement vocal ou interview avec horodatage.',
        suggestedDeliverables: ['Fichier texte propre Word/Google Doc', 'Horodatage des interventions'],
      },
      {
        id: 'proofreading',
        name: 'Correction & Relecture orthographique',
        suggestedPriceDH: 70,
        timeEstimateHours: 12,
        templateTitle: 'Correction orthographique et syntaxique de document',
        templateDesc: 'Relecture minutieuse de document (rapport, mémoire, email) pour éliminer les fautes.',
        suggestedDeliverables: ['Version corrigée avec suivi des modifications', 'Version propre finale en PDF/Word'],
      },
    ],
  },
  {
    id: 'design',
    key: 'design',
    name: 'Graphisme & Design',
    icon: '🎨',
    color: 'purple',
    accentBg: 'bg-purple-50',
    accentBorder: 'border-purple-200',
    accentText: 'text-purple-700',
    description: 'Logos, menus de restaurant, identités visuelles, visuels pour réseaux sociaux, affiches et packagings.',
    subcategories: [
      {
        id: 'logo-branding',
        name: 'Logo & Identité visuelle',
        suggestedPriceDH: 300,
        timeEstimateHours: 48,
        templateTitle: 'Création d’un logo moderne vectoriel (3 propositions)',
        templateDesc: 'Conception d’un logo professionnel épuré avec déclinaisons couleurs, police et fichiers sources.',
        suggestedDeliverables: ['Fichiers vectoriels modifiables (AI, EPS, SVG)', 'Exports haute définition (PNG fond transparent, JPG, PDF)'],
      },
      {
        id: 'social-media-posts',
        name: 'Visuels pour Réseaux Sociaux (Instagram/FB)',
        suggestedPriceDH: 200,
        timeEstimateHours: 24,
        templateTitle: 'Pack de 5 visuels pour publications Instagram / Facebook',
        templateDesc: 'Création de visuels attractifs respectant la charte graphique de la marque.',
        suggestedDeliverables: ['Exports PNG / JPG au format 1:1 et 9:16', 'Fichiers sources Canva ou Photoshop'],
      },
      {
        id: 'restaurant-menu',
        name: 'Menus de restaurant & Cartes de visite',
        suggestedPriceDH: 250,
        timeEstimateHours: 24,
        templateTitle: 'Mise en page et design du menu pour café / restaurant',
        templateDesc: 'Création du menu imprimable (recto-verso ou livret) avec photos produits et tarifs clairs.',
        suggestedDeliverables: ['Fichier PDF haute définition prêt pour impression', 'Fichier source PSD/AI ou Canva'],
      },
      {
        id: 'flyers-posters',
        name: 'Flyers, Dépliants & Affiches',
        suggestedPriceDH: 180,
        timeEstimateHours: 24,
        templateTitle: 'Conception d’un flyer promotionnel A5',
        templateDesc: 'Design percutant pour promotion ou événement avec textes et offres mis en valeur.',
        suggestedDeliverables: ['Fichier PDF HD avec traits de coupe', 'Export JPG pour diffusion digitale'],
      },
      {
        id: 'photo-editing',
        name: 'Retouche photo & Détourage produit',
        suggestedPriceDH: 100,
        timeEstimateHours: 12,
        templateTitle: 'Détourage sur fond blanc de 20 photos produits',
        templateDesc: 'Suppression d’arrière-plan, ombrage naturel et amélioration des contrastes pour e-commerce.',
        suggestedDeliverables: ['20 photos détourées en PNG transparent', 'Versions optimisées légères pour le web'],
      },
    ],
  },
  {
    id: 'development',
    key: 'development',
    name: 'Web & E-commerce',
    icon: '💻',
    color: 'blue',
    accentBg: 'bg-blue-50',
    accentBorder: 'border-blue-200',
    accentText: 'text-blue-700',
    description: 'Boutiques YouCan, Shopify, sites WordPress, correction de bugs et intégration de paiement CMI.',
    subcategories: [
      {
        id: 'youcan-shopify',
        name: 'Boutique YouCan Shop / Shopify',
        suggestedPriceDH: 350,
        timeEstimateHours: 48,
        templateTitle: 'Paramétrage complet boutique YouCan / Shopify',
        templateDesc: 'Installation du thème, configuration du panier, mode de livraison au Maroc et intégration des produits.',
        suggestedDeliverables: ['Boutique 100% opérationnelle et testée', 'Guide rapide d’administration'],
      },
      {
        id: 'wordpress-site',
        name: 'Site vitrine WordPress / Landing Page',
        suggestedPriceDH: 500,
        timeEstimateHours: 72,
        templateTitle: 'Création d’un site vitrine responsive 3 pages',
        templateDesc: 'Installation WordPress + Elementor, pages Accueil, Services et Contact avec formulaire.',
        suggestedDeliverables: ['Site en ligne connecté au nom de domaine', 'Formulaire de contact fonctionnel avec alertes'],
      },
      {
        id: 'bug-fix',
        name: 'Correction de bug & Modifications',
        suggestedPriceDH: 150,
        timeEstimateHours: 6,
        templateTitle: 'Correction d’un bug d’affichage mobile sur site web',
        templateDesc: 'Résolution rapide d’un problème CSS/JavaScript survenu sur la version smartphone.',
        suggestedDeliverables: ['Code corrigé et vérifié sur plusieurs navigateurs', 'Rapport bref des modifications faites'],
      },
      {
        id: 'cmi-payment',
        name: 'Intégration Passerelle CMI / Paiement',
        suggestedPriceDH: 400,
        timeEstimateHours: 24,
        templateTitle: 'Intégration du module de paiement bancaire CMI',
        templateDesc: 'Connexion de la passerelle CMI sur WooCommerce ou site sur-mesure avec tests de validation.',
        suggestedDeliverables: ['Module CMI validé en mode test et production', 'Paiements par carte marocaine fonctionnels'],
      },
    ],
  },
  {
    id: 'assistance',
    key: 'assistance',
    name: 'Saisie & Administratif',
    icon: '📊',
    color: 'amber',
    accentBg: 'bg-amber-50',
    accentBorder: 'border-amber-200',
    accentText: 'text-amber-700',
    description: 'Saisie sous Excel, collecte de données, traitement de factures, conversion de documents et secrétariat.',
    subcategories: [
      {
        id: 'excel-data-entry',
        name: 'Saisie de données sous Excel / Sheets',
        suggestedPriceDH: 120,
        timeEstimateHours: 24,
        templateTitle: 'Saisie de 150 factures et rapprochement dans Excel',
        templateDesc: 'Recopie précise des montants, dates, noms de clients et formules de calcul automatique.',
        suggestedDeliverables: ['Fichier Excel propre avec formules vérifiées', 'Zéro erreur de report'],
      },
      {
        id: 'pdf-word-conversion',
        name: 'Conversion PDF vers Word / Excel',
        suggestedPriceDH: 80,
        timeEstimateHours: 12,
        templateTitle: 'Reformatage et conversion de 20 pages PDF scannées en Word',
        templateDesc: 'Reconstruction exacte des tableaux, polices et mise en page éditable.',
        suggestedDeliverables: ['Fichier Word modifiable fidèle à l’original', 'Mise en page propre'],
      },
      {
        id: 'web-research-leads',
        name: 'Recherche web & Collecte de contacts',
        suggestedPriceDH: 150,
        timeEstimateHours: 24,
        templateTitle: 'Recherche de 50 contacts d’entreprises ciblées au Maroc',
        templateDesc: 'Collecte de coordonnées (Nom, Ville, Téléphone, Email, Site web) dans un tableur.',
        suggestedDeliverables: ['Fichier Excel avec les 50 fiches complètes et vérifiées', 'Contacts récents'],
      },
      {
        id: 'whatsapp-customer-service',
        name: 'Service client WhatsApp / Réception appels',
        suggestedPriceDH: 200,
        timeEstimateHours: 24,
        templateTitle: 'Gestion des messages WhatsApp clients pendant 3 jours',
        templateDesc: 'Réponse rapide et courtoise aux demandes d’informations et confirmations de commandes.',
        suggestedDeliverables: ['Rapport quotidien des échanges et commandes traitées', 'Historique des messages'],
      },
    ],
  },
  {
    id: 'marketing',
    key: 'marketing',
    name: 'Marketing & Vidéo',
    icon: '📱',
    color: 'rose',
    accentBg: 'bg-rose-50',
    accentBorder: 'border-rose-200',
    accentText: 'text-rose-700',
    description: 'Montage TikTok / Reels, voix off en Darija, publicités sponsorisées et gestion de réseaux sociaux.',
    subcategories: [
      {
        id: 'reels-tiktok-editing',
        name: 'Montage Vidéo TikTok / Instagram Reels',
        suggestedPriceDH: 180,
        timeEstimateHours: 24,
        templateTitle: 'Montage dynamique de 3 vidéos Reels / TikTok',
        templateDesc: 'Ajout de sous-titres animés, musique tendance, transitions fluides et effets captivants.',
        suggestedDeliverables: ['3 vidéos MP4 verticales (9:16) haute qualité', 'Sous-titres synchronisés et musique libre de droits'],
      },
      {
        id: 'voiceover-darija',
        name: 'Voix Off en Darija / Arabe / Français',
        suggestedPriceDH: 150,
        timeEstimateHours: 12,
        templateTitle: 'Enregistrement voix off en Darija marocaine (1 minute)',
        templateDesc: 'Lecture professionnelle avec ton vendeur ou chaleureux, son studio sans bruit de fond.',
        suggestedDeliverables: ['Fichier audio WAV / MP3 nettoyé et masterisé', 'Deux prises d’intonations différentes'],
      },
      {
        id: 'facebook-ads-setup',
        name: 'Campagne Publicitaire Facebook & Instagram',
        suggestedPriceDH: 250,
        timeEstimateHours: 24,
        templateTitle: 'Paramétrage d’une campagne publicitaire Facebook Ads ciblée',
        templateDesc: 'Création du ciblage géographique et démographique au Maroc, configuration du pixel et budget.',
        suggestedDeliverables: ['Campagne configurée prête au lancement', 'Rapport de paramétrage avec conseils de budget'],
      },
    ],
  },
  {
    id: 'local',
    key: 'micro',
    name: 'Services sur le terrain & Micro-tâches',
    icon: '📍',
    color: 'amber',
    accentBg: 'bg-amber-50',
    accentBorder: 'border-amber-200',
    accentText: 'text-amber-800',
    description: 'Démarches administratives, livraison de plis, visites de contrôle, tests d’applications et tâches rapides.',
    subcategories: [
      {
        id: 'admin-errands',
        name: 'Démarches & Dépôt de documents urgents',
        suggestedPriceDH: 120,
        timeEstimateHours: 6,
        templateTitle: 'Dépôt d’un pli ou document urgent en ville',
        templateDesc: 'Récupération d’un document et remise en mains propres contre récépissé daté et signé.',
        suggestedDeliverables: ['Photo du récépissé avec cachet ou signature', 'Confirmation immédiate par message'],
      },
      {
        id: 'site-visit-inspection',
        name: 'Visite de contrôle & Photos sur place',
        suggestedPriceDH: 150,
        timeEstimateHours: 12,
        templateTitle: 'Vérification sur place et reportage photo d’un bien / local',
        templateDesc: 'Déplacement sur place pour prendre 10 photos nettes et vérifier l’état général.',
        suggestedDeliverables: ['Album de 10 photos géolocalisées et datées', 'Bref compte-rendu de visite'],
      },
      {
        id: 'app-testing',
        name: 'Test d’application mobile & Avis utilisateur',
        suggestedPriceDH: 80,
        timeEstimateHours: 6,
        templateTitle: 'Test complet du parcours d’achat sur application mobile',
        templateDesc: 'Tester l’inscription, la recherche, le panier et signaler tous les blocages rencontrés.',
        suggestedDeliverables: ['Rapport avec captures d’écran des bugs éventuels', 'Avis détaillé sur la facilité d’utilisation'],
      },
      {
        id: 'quick-microtask',
        name: 'Micro-tâche express (< 1 heure)',
        suggestedPriceDH: 50,
        timeEstimateHours: 2,
        templateTitle: 'Micro-tâche rapide en ligne',
        templateDesc: 'Exécution d’une petite tâche simple et directe ne nécessitant pas de compétences complexes.',
        suggestedDeliverables: ['Preuve d’exécution ou lien final validé'],
      },
    ],
  },
];

export const MOROCCAN_CITIES = [
  'Casablanca',
  'Rabat',
  'Marrakech',
  'Tanger',
  'Fès',
  'Agadir',
  'Salé',
  'Meknès',
  'Oujda',
  'Kénitra',
  'Tétouan',
  'Mohammédia',
  'El Jadida',
  'Nador',
  'Béni Mellal',
  'Autre ville au Maroc',
];
