import { Task, UserProfile, WalletTransaction } from '@/types/database';
import { Locale } from './i18n/types';

export const initialUser: UserProfile = {
  id: 'usr_me_1',
  email: 'aero@example.com',
  fullName: 'Aero Mehdi',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  activeRole: 'PERFORMER',
  balanceAvailable: 285.5,
  balanceEscrow: 75.0,
  createdAt: '2024-01-15T10:00:00Z',

  // Performer stats (Level 3 Pro)
  performerTier: 'level_3',
  performerXp: 780,
  performerRating: 4.96,
  performerReviewsCount: 48,
  performerCompletedTasks: 52,
  passedQualification: true,

  // Customer stats
  customerRating: 5.0,
  customerTotalSpent: 640.0,
  customerTasksPosted: 11,
};

export interface LocalizedTaskContent {
  title: Record<Locale, string>;
  description: Record<Locale, string>;
  requiredProofs: Record<Locale, string[]>;
}

export const taskTranslations: Record<string, LocalizedTaskContent> = {
  tsk_101: {
    title: {
      ru: "Настройка и оптимизация магазина YouCan / Shopify",
      fr: "Configuration et personnalisation boutique YouCan / Shopify",
      ar: "إعداد وتخصيص متجر إلكتروني على YouCan / Shopify",
      en: "Setup & optimization of YouCan / Shopify online store",
      es: "Configuración y optimización de tienda YouCan / Shopify",
    },
    description: {
      ru: "Требуется настроить тему YouCan Shop, подключить оплату CMI и загрузить первые 15 товаров с описаниями на арабском и французском.",
      fr: "Configuration complète d’une boutique YouCan Shop : installation du thème, mode de livraison au Maroc, intégration des 15 premiers produits avec descriptions soignées.",
      ar: "إعداد كامل لمتجر YouCan Shop: تثبيت القالب، ضبط وسائل التوصيل في المغرب، وإدخال أول 15 منتجاً مع صور ووصف احترافي.",
      en: "Full setup of a YouCan Shop store: theme configuration, Moroccan shipping rates, and upload of 15 initial products with clean descriptions.",
      es: "Configuración completa de tienda YouCan Shop: instalación del tema, métodos de envío en Marruecos y carga de los primeros 15 productos con fotos.",
    },
    requiredProofs: {
      ru: [
        "Ссылка на опубликованный и рабочий магазин",
        "Скриншоты настроенных страниц доставки и корзины",
      ],
      fr: [
        "Lien direct vers la boutique opérationnelle",
        "Captures d’écran de la configuration panier et livraison",
      ],
      ar: [
        "رابط مباشر للمتجر بعد النشر والعمل",
        "لقطات شاشة لصفحات السلة وإعدادات التوصيل",
      ],
      en: [
        "Live URL link to the fully working store",
        "Screenshots of cart and Moroccan delivery settings",
      ],
      es: [
        "Enlace directo a la tienda operativa",
        "Capturas de pantalla del carrito y configuración de envíos",
      ],
    },
  },
  tsk_102: {
    title: {
      ru: "Создание логотипа и меню для кафе-ресторана в Касабланке",
      fr: "Création de logo & design du menu pour café/restaurant à Casablanca",
      ar: "تصميم شعار وقائمة طعام لمطعم ومقهى بالدار البيضاء",
      en: "Logo design & menu layout for café/restaurant in Casablanca",
      es: "Diseño de logotipo y menú para café/restaurante en Casablanca",
    },
    description: {
      ru: "Нужен стильный логотип и двухстороннее меню A4 для нового заведения в районе Готье (Касабланка). Форматы для печати PDF + PSD/AI.",
      fr: "Recherche d’un graphiste pour concevoir le logo et la carte des boissons/plats (recto-verso format A4) pour un nouveau café à Casablanca. Fichiers prêts pour l’imprimeur.",
      ar: "مطلوب مصمم جرافيك لابتكار شعار وتصميم قائمة الطعام والمشروبات (وجهين A4) لمقهى جديد بالدار البيضاء. تسليم ملفات جاهزة للطباعة.",
      en: "Looking for a graphic designer to create the logo and 2-page A4 food & drink menu for a new café in Casablanca. Print-ready files required.",
      es: "Buscamos diseñador gráfico para crear logo y menú de 2 caras A4 para un nuevo café en Casablanca. Archivos listos para imprenta.",
    },
    requiredProofs: {
      ru: [
        "Векторные исходники .AI или .PSD со слоями",
        "Печатный PDF высокого разрешения (300 DPI)",
      ],
      fr: [
        "Fichiers sources vectoriels .AI ou .PSD avec calques",
        "PDF haute définition (300 DPI) prêt pour impression",
      ],
      ar: [
        "ملفات المصدر المفتوحة .AI أو .PSD مع الطبقات",
        "ملف PDF عالي الدقة (300 DPI) مجهز للطباعة",
      ],
      en: [
        "Vector source files (.AI or layered .PSD)",
        "High-res print-ready PDF (300 DPI)",
      ],
      es: [
        "Archivos fuente vectoriales .AI o .PSD con capas",
        "PDF de alta resolución (300 DPI) listo para imprimir",
      ],
    },
  },
  tsk_103: {
    title: {
      ru: "Сверка и ввод 180 счетов-фактур в Excel",
      fr: "Saisie de 180 factures et rapprochement sous Excel",
      ar: "إدخال ومطابقة 180 فاتورة تجارية في جدول Excel",
      en: "Data entry of 180 invoices & reconciliation in Excel",
      es: "Introducción y cuadre de 180 facturas en Excel",
    },
    description: {
      ru: "Ввод данных из отсканированных PDF счетов в готовый шаблон Excel. Точность чисел, проверка НДС и формул.",
      fr: "Saisie minutieuse des montants, numéros de factures, dates et TVA depuis des PDF scannés vers notre matrice Excel. Rapprochement avec zéro erreur.",
      ar: "إدخال دقيق للبيانات والمبالغ وتواريخ الفواتير وأرقامها من ملفات PDF الممسوحة ضوئياً إلى نموذج Excel مع مراجعة المجاميع.",
      en: "Accurate entry of invoice numbers, dates, amounts and VAT from scanned PDFs into our Excel template with total reconciliation.",
      es: "Introducción rigurosa de 180 facturas desde PDFs escaneados a plantilla Excel con comprobación de subtotales e IVA.",
    },
    requiredProofs: {
      ru: ["Файл Excel .xlsx с заполненными данными и формулами"],
      fr: ["Fichier Excel .xlsx complet avec formules vérifiées"],
      ar: ["ملف Excel بصيغة .xlsx مع التحقق من كافة العمليات الحسابية"],
      en: ["Completed Excel .xlsx file with verified totals and formulas"],
      es: ["Archivo Excel .xlsx completado con fórmulas verificadas"],
    },
  },
  tsk_104: {
    title: {
      ru: "Перевод коммерческого договора с арабского на французский",
      fr: "Traduction d’un contrat commercial Arabe vers Français (5 pages)",
      ar: "ترجمة عقد تجاري من العربية إلى الفرنسية (5 صفحات)",
      en: "Translation of commercial agreement from Arabic to French (5 pages)",
      es: "Traducción de contrato comercial de Árabe a Francés (5 páginas)",
    },
    description: {
      ru: "Юридический и коммерческий перевод партнерского соглашения (5 страниц, ~1800 слов). Строгое соблюдение терминологии марокканского права.",
      fr: "Traduction soignée et rigoureuse d’un contrat de partenariat commercial de 5 pages de l’Arabe standard vers le Français juridique marocain.",
      ar: "ترجمة دقيقة ومحكمة لعقد شراكة تجارية يقع في 5 صفحات من العربية الفصحى إلى الفرنسية القانونية المعتمدة في المغرب.",
      en: "Accurate translation of a 5-page commercial partnership contract from Arabic to French respecting Moroccan legal standards.",
      es: "Traducción precisa de contrato de sociedad comercial de 5 páginas de Árabe a Francés jurídico marroquí.",
    },
    requiredProofs: {
      ru: ["Итоговый документ Word (.docx) и PDF с точным форматированием"],
      fr: ["Document finalisé en format Word (.docx) et PDF propre"],
      ar: ["الملف المترجم بصيغتي Word (.docx) و PDF مطابق للتنسيق الأصلي"],
      en: ["Finalized document in Word (.docx) and clean PDF format"],
      es: ["Documento traducido en Word (.docx) y PDF con maquetación limpia"],
    },
  },
  tsk_105: {
    title: {
      ru: "Монтаж 3 коротких роликов для TikTok / Instagram Reels",
      fr: "Montage dynamique de 3 vidéos pour TikTok & Instagram Reels",
      ar: "مونتاج احترافي وديناميكي لـ 3 مقاطع فيديو لـ TikTok و Reels",
      en: "Dynamic video editing of 3 clips for TikTok & Instagram Reels",
      es: "Edición dinámica de 3 vídeos para TikTok e Instagram Reels",
    },
    description: {
      ru: "Монтаж 3 вертикальных видео (9:16) по 40 секунд: динамичные склейки, анимированные субтитры, звуковые эффекты и трендовая музыка.",
      fr: "Montage de 3 vidéos verticales (9:16) percutantes pour la promotion d’une marque locale : sous-titres animés, transitions dynamiques et musique tendance.",
      ar: "مونتاج 3 فيديوهات عمودية (9:16) مدتها 40 ثانية للترويج لعلامة تجارية محلية: نصوص متحركة، انتقالات سريعة، ومؤثرات صوتية.",
      en: "Editing of 3 vertical videos (9:16, 40s each) for local brand promo: animated captions, crisp cuts, and trending sound design.",
      es: "Edición de 3 vídeos verticales (9:16) de 40 segundos: subtítulos dinámicos, transiciones fluidas y música en tendencia.",
    },
    requiredProofs: {
      ru: ["3 видеофайла в формате MP4 1080x1920 Full HD"],
      fr: ["3 fichiers vidéo finaux MP4 Full HD (1080x1920)"],
      ar: ["3 ملفات فيديو نهائية بصيغة MP4 بدقة عالية Full HD"],
      en: ["3 final video files in MP4 Full HD (1080x1920)"],
      es: ["3 archivos de vídeo finales MP4 en Full HD (1080x1920)"],
    },
  },
  tsk_106: {
    title: {
      ru: "Срочная подача документов в администрацию в Рабате",
      fr: "Dépôt physique urgent de dossier administratif à Rabat",
      ar: "إيداع ملف إداري مستعجل في إدارة عمومية بالرباط",
      en: "Urgent physical delivery of administrative documents in Rabat",
      es: "Entrega física urgente de expediente administrativo en Rabat",
    },
    description: {
      ru: "Требуется забрать запечатанный пакет в центре Рабата и сдать в канцелярию с получением регистрационного штампа.",
      fr: "Mission sur le terrain à Rabat : récupération d’un pli fermé et dépôt au bureau d’ordre avec accusé de réception tamponné et daté.",
      ar: "مهمة ميدانية بالرباط: استلام ظرف مغلق وإيداعه بمكتب الضبط وأخذ وصل الإيداع مختوماً ومؤرخاً.",
      en: "On-site errand in Rabat: pickup of a sealed envelope and delivery to registry office with a stamped and dated receipt acknowledgment.",
      es: "Gestión presencial en Rabat: recogida de sobre cerrado y entrega en registro con sello oficial fechado.",
    },
    requiredProofs: {
      ru: ["Четкое фото расписки/штампа о принятии документов"],
      fr: ["Photo nette du récépissé d’enregistrement avec cachet officiel"],
      ar: ["صورة واضحة لوصل الإيداع يحمل الطابع والتاريخ الرسمي"],
      en: ["Clear photograph of the officially stamped receipt acknowledgment"],
      es: ["Fotografía clara del justificante con sello oficial fechado"],
    },
  },
  tsk_107: {
    title: {
      ru: "Проверенные отзывы Google Maps для ресторана в Касабланке (10 мест)",
      fr: "Avis Google Maps 5 étoiles vérifiés pour restaurant à Casablanca",
      ar: "تقييمات 5 نجوم موثقة على خرائط جوجل لمطعم بالدار البيضاء",
      en: "Verified 5-star Google Maps reviews for Casablanca restaurant",
      es: "Reseñas verificadas de 5 estrellas en Google Maps para restaurante en Casablanca",
    },
    description: {
      ru: "Требуется оставить честный и развернутый отзыв с активного марокканского аккаунта Google с фото.",
      fr: "Publier un avis détaillé et positif avec compte Google actif au Maroc. Mentionner l'ambiance et joindre une capture d'écran.",
      ar: "نشر تقييم إيجابي ومفصل بحساب جوجل نشط في المغرب مع إرفاق لقطة شاشة للتأكيد.",
      en: "Post a detailed positive review with an active Moroccan Google account. Mention ambiance and attach screenshot.",
      es: "Publicar una reseña positiva detallada con cuenta activa de Google en Marruecos y captura de pantalla.",
    },
    requiredProofs: {
      ru: ["Скриншот опубликованного отзыва"],
      fr: ["Capture d’écran de l’avis publié avec nom du compte"],
      ar: ["لقطة شاشة للتقييم المنشور مع اسم الحساب"],
      en: ["Screenshot of the published review showing account name"],
      es: ["Captura de pantalla de la reseña publicada"],
    },
  },
  tsk_108: {
    title: {
      ru: "Тестирование мобильного приложения на смартфонах Samsung / Android",
      fr: "Test d'application mobile et inscription sur Samsung / Android",
      ar: "اختبار تطبيق هاتفي والتسجيل على هواتف سامسونج وأندرويد",
      en: "Mobile app testing & registration on Samsung / Android",
      es: "Pruebas de aplicación móvil y registro en Samsung / Android",
    },
    description: {
      ru: "Установить приложение из Google Play, пройти регистрацию по SMS и прислать скриншоты.",
      fr: "Installer l'application sur smartphone Android (réseau marocain), tester la réception du code OTP et envoyer 3 captures.",
      ar: "تثبيت التطبيق على هاتف أندرويد وتجربة استلام كود OTP وإرسال 3 لقطات شاشة.",
      en: "Install app on Android (Moroccan network), test SMS OTP verification, and submit 3 screenshots.",
      es: "Instalar aplicación en Android (red marroquí), probar código OTP y enviar 3 capturas.",
    },
    requiredProofs: {
      ru: ["3 скриншота этапов тестирования и модель смартфона"],
      fr: ["3 captures d’écran des étapes clés et modèle du téléphone"],
      ar: ["3 لقطات شاشة للمراحل الأساسية مع نوع الهاتف"],
      en: ["3 screenshots of key steps and smartphone model"],
      es: ["3 capturas de pantalla de los pasos clave y modelo de móvil"],
    },
  },
};

export const initialTasks: Task[] = [
  {
    id: 'tsk_101',
    title: taskTranslations.tsk_101.title.fr,
    description: taskTranslations.tsk_101.description.fr,
    category: 'development',
    subCategory: 'Boutique YouCan Shop / Shopify',
    locationMode: 'online',
    taskMode: 'single',
    status: 'OPEN',
    reward: 35.0,
    platformFee: 3.5,
    totalBudget: 38.5,
    timeLimitHours: 48,
    minLevelRequired: 1,
    clientId: 'cli_01',
    clientName: 'Yassine K. (E-com)',
    clientAvatar:
      'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80',
    clientRating: 4.9,
    clientHireRate: 98,
    requiredProofs: taskTranslations.tsk_101.requiredProofs.fr,
    applicantsCount: 5,
    createdAt: 'Il y a 15 min',
  },
  {
    id: 'tsk_102',
    title: taskTranslations.tsk_102.title.fr,
    description: taskTranslations.tsk_102.description.fr,
    category: 'design',
    subCategory: 'Logo & Menus restaurant',
    locationMode: 'in_person',
    city: 'Casablanca',
    taskMode: 'single',
    status: 'OPEN',
    reward: 25.0,
    platformFee: 2.5,
    totalBudget: 27.5,
    timeLimitHours: 24,
    minLevelRequired: 1,
    clientId: 'cli_02',
    clientName: 'Karim B. (Gérant Café)',
    clientAvatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    clientRating: 5.0,
    clientHireRate: 100,
    requiredProofs: taskTranslations.tsk_102.requiredProofs.fr,
    applicantsCount: 8,
    createdAt: 'Il y a 45 min',
  },
  {
    id: 'tsk_103',
    title: taskTranslations.tsk_103.title.fr,
    description: taskTranslations.tsk_103.description.fr,
    category: 'assistance',
    subCategory: 'Saisie de données Excel',
    locationMode: 'online',
    taskMode: 'single',
    status: 'OPEN',
    reward: 12.0,
    platformFee: 1.2,
    totalBudget: 13.2,
    timeLimitHours: 12,
    minLevelRequired: 1,
    clientId: 'cli_03',
    clientName: 'Rachid M. (Comptable)',
    clientAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    clientRating: 4.85,
    clientHireRate: 94,
    requiredProofs: taskTranslations.tsk_103.requiredProofs.fr,
    applicantsCount: 6,
    createdAt: 'Il y a 2h',
  },
  {
    id: 'tsk_104',
    title: taskTranslations.tsk_104.title.fr,
    description: taskTranslations.tsk_104.description.fr,
    category: 'copywriting',
    subCategory: 'Traduction Arabe ⇄ Français',
    locationMode: 'online',
    taskMode: 'single',
    status: 'IN_PROGRESS',
    reward: 15.0,
    platformFee: 1.5,
    totalBudget: 16.5,
    timeLimitHours: 24,
    minLevelRequired: 1,
    clientId: 'cli_04',
    clientName: 'Nawal T. (Cabinet)',
    clientAvatar:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    clientRating: 4.95,
    clientHireRate: 96,
    requiredProofs: taskTranslations.tsk_104.requiredProofs.fr,
    applicantsCount: 4,
    assignedToId: 'usr_me_1',
    assignedToName: 'Aero Mehdi',
    assignedAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    createdAt: 'Il y a 3h',
  },
  {
    id: 'tsk_105',
    title: taskTranslations.tsk_105.title.fr,
    description: taskTranslations.tsk_105.description.fr,
    category: 'marketing',
    subCategory: 'Montage Vidéo TikTok / Reels',
    locationMode: 'online',
    taskMode: 'single',
    status: 'OPEN',
    reward: 18.0,
    platformFee: 1.8,
    totalBudget: 19.8,
    timeLimitHours: 24,
    minLevelRequired: 1,
    clientId: 'cli_05',
    clientName: 'Amine K. (Créateur)',
    clientAvatar:
      'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    clientRating: 4.9,
    clientHireRate: 95,
    requiredProofs: taskTranslations.tsk_105.requiredProofs.fr,
    applicantsCount: 11,
    createdAt: 'Il y a 10 min',
  },
  {
    id: 'tsk_106',
    title: taskTranslations.tsk_106.title.fr,
    description: taskTranslations.tsk_106.description.fr,
    category: 'micro',
    subCategory: 'Démarches & Dépôt urgent',
    locationMode: 'in_person',
    city: 'Rabat',
    taskMode: 'single',
    status: 'OPEN',
    reward: 12.0,
    platformFee: 1.2,
    totalBudget: 13.2,
    timeLimitHours: 6,
    minLevelRequired: 1,
    clientId: 'cli_06',
    clientName: 'Cabinet Juridique Rabat',
    clientAvatar:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
    clientRating: 4.85,
    clientHireRate: 94,
    requiredProofs: taskTranslations.tsk_106.requiredProofs.fr,
    applicantsCount: 3,
    createdAt: 'Il y a 30 min',
  },
  {
    id: 'tsk_107',
    title: taskTranslations.tsk_107.title.fr,
    description: taskTranslations.tsk_107.description.fr,
    category: 'micro',
    subCategory: 'Avis Google Maps vérifiés',
    locationMode: 'online',
    taskMode: 'multi',
    targetExecutionsCount: 10,
    unitPriceDH: 15,
    status: 'OPEN',
    reward: 15.0,
    platformFee: 1.5,
    totalBudget: 16.5,
    timeLimitHours: 6,
    minLevelRequired: 1,
    clientId: 'cli_07',
    clientName: 'Restaurant La Table Bleue',
    clientAvatar:
      'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&auto=format&fit=crop&q=80',
    clientRating: 4.9,
    clientHireRate: 100,
    requiredProofs: taskTranslations.tsk_107.requiredProofs.fr,
    applicantsCount: 7,
    createdAt: 'Il y a 5 min',
  },
  {
    id: 'tsk_108',
    title: taskTranslations.tsk_108.title.fr,
    description: taskTranslations.tsk_108.description.fr,
    category: 'micro',
    subCategory: 'Test application Android',
    locationMode: 'online',
    taskMode: 'multi',
    targetExecutionsCount: 5,
    unitPriceDH: 25,
    status: 'OPEN',
    reward: 12.5,
    platformFee: 1.25,
    totalBudget: 13.75,
    timeLimitHours: 4,
    minLevelRequired: 1,
    clientId: 'cli_08',
    clientName: 'Fintech Maroc SAS',
    clientAvatar:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80',
    clientRating: 5.0,
    clientHireRate: 98,
    requiredProofs: taskTranslations.tsk_108.requiredProofs.fr,
    applicantsCount: 4,
    createdAt: 'Il y a 20 min',
  },
];

export const transactionTranslations: Record<string, Record<Locale, string>> = {
  tx_901: {
    ru: 'Оплата за задание #tsk_102 "Дизайн меню ресторана"',
    fr: 'Paiement reçu pour tâche #tsk_102 "Design menu restaurant"',
    ar: 'دفعة مستلمة للمهمة #tsk_102 "تصميم قائمة طعام لمطعم"',
    en: 'Payout received for task #tsk_102 "Restaurant menu design"',
    es: 'Pago recibido por tarea #tsk_102 "Diseño de menú de restaurante"',
  },
  tx_902: {
    ru: 'Пополнение баланса через карту CMI / Банк',
    fr: 'Approvisionnement du compte via Carte CMI / Virement',
    ar: 'شحن الحساب عبر بطاقة CMI البنكية / تحويل',
    en: 'Wallet deposit via Moroccan Bank / CMI Card',
    es: 'Recarga de cuenta con tarjeta CMI / Transferencia',
  },
  tx_903: {
    ru: 'Блокировка в эскроу для публикации задачи #tsk_101',
    fr: 'Séquestre Daman bloqué pour publication tâche #tsk_101',
    ar: 'حجز رصيد الضمان لنشر المهمة #tsk_101',
    en: 'Escrow deposit locked for task publication #tsk_101',
    es: 'Depósito en garantía retenido para tarea #tsk_101',
  },
  tx_904: {
    ru: 'Комиссия сервиса Tâches (10%)',
    fr: 'Frais de gestion & Séquestre Daman (10%)',
    ar: 'رسوم حماية الضمان والخدمة (10%)',
    en: 'Platform escrow and service fee (10%)',
    es: 'Comisión de custodia y gestión (10%)',
  },
};

export const initialTransactions: WalletTransaction[] = [
  {
    id: 'tx_901',
    userId: 'usr_me_1',
    type: 'ESCROW_RELEASE',
    amount: 25.0,
    currency: 'EUR',
    description: transactionTranslations.tx_901.fr,
    createdAt: 'Hier à 18:20',
    status: 'COMPLETED',
  },
  {
    id: 'tx_902',
    userId: 'usr_me_1',
    type: 'DEPOSIT',
    amount: 50.0,
    currency: 'EUR',
    description: transactionTranslations.tx_902.fr,
    createdAt: '25 Sep 2026',
    status: 'COMPLETED',
  },
  {
    id: 'tx_903',
    userId: 'usr_me_1',
    type: 'ESCROW_LOCK',
    amount: -38.5,
    currency: 'EUR',
    description: transactionTranslations.tx_903.fr,
    createdAt: '24 Sep 2026',
    status: 'COMPLETED',
  },
  {
    id: 'tx_904',
    userId: 'usr_me_1',
    type: 'COMMISSION',
    amount: -3.5,
    currency: 'EUR',
    description: transactionTranslations.tx_904.fr,
    createdAt: 'Hier à 18:20',
    status: 'COMPLETED',
  },
];

export function getLocalizedTask(task: Task, locale: Locale): Task {
  const trans = taskTranslations[task.id];
  if (!trans) return task;
  return {
    ...task,
    title: trans.title[locale] || task.title,
    description: trans.description[locale] || task.description,
    requiredProofs: trans.requiredProofs[locale] || task.requiredProofs,
  };
}

export function getLocalizedTransaction(
  tx: WalletTransaction,
  locale: Locale
): WalletTransaction {
  const trans = transactionTranslations[tx.id];
  if (!trans) return tx;
  return {
    ...tx,
    description: trans[locale] || tx.description,
  };
}
