import { Task, UserProfile, WalletTransaction } from '@/types/database';

export const initialUser: UserProfile = {
  id: 'usr_me_1',
  email: 'aero@example.com',
  fullName: 'Aero Mehdi',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  activeRole: 'PERFORMER',
  balanceAvailable: 285.50,
  balanceEscrow: 75.00,
  createdAt: '2024-01-15T10:00:00Z',

  // Performer stats (UNU-style Level 3 Pro)
  performerTier: 'level_3',
  performerXp: 780, // out of 1000 for level 4
  performerRating: 4.96,
  performerReviewsCount: 48,
  performerCompletedTasks: 52,
  passedQualification: true,

  // Customer stats (Work-zilla style)
  customerRating: 5.0,
  customerTotalSpent: 640.00,
  customerTasksPosted: 11,
};

export const initialTasks: Task[] = [
  {
    id: 'tsk_101',
    title: "Correction responsive Tailwind CSS & formulaire de contact Next.js",
    description: "Nous avons une landing page Next.js dont le menu mobile se chevauche sur iPhone 13/14 et le formulaire de contact nécessite une validation Zod avec envoi d'email via Resend. Code propre et testé requis.",
    category: 'development',
    status: 'OPEN',
    reward: 45.00,
    platformFee: 5.00,
    totalBudget: 50.00,
    timeLimitHours: 4,
    minLevelRequired: 2,
    clientId: 'cli_01',
    clientName: 'Studio Digital Paris',
    clientAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80',
    clientRating: 4.9,
    clientHireRate: 98,
    requiredProofs: [
      "Lien vers la Pull Request GitHub ou commit vérifiable",
      "Vidéo de 30s ou capture d'écran du menu sur viewport mobile (390px)"
    ],
    applicantsCount: 3,
    createdAt: 'Il y a 25 min',
  },
  {
    id: 'tsk_102',
    title: "Création d'un logo vectoriel minimaliste + favicon SVG pour startup IA",
    description: "Recherche d'un graphiste pour concevoir un logo moderne et épuré pour 'SynapseAI'. Palette sobre (noir/blanc + touche néon vert/lime). Livrables en SVG, PNG transparent haute résolution et favicon.ico.",
    category: 'design',
    status: 'OPEN',
    reward: 70.00,
    platformFee: 7.00,
    totalBudget: 77.00,
    timeLimitHours: 24,
    minLevelRequired: 1,
    clientId: 'cli_02',
    clientName: 'Karim B. (Founder)',
    clientAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    clientRating: 5.0,
    clientHireRate: 100,
    requiredProofs: [
      "Fichiers sources vectoriels .SVG et .AI",
      "Fichier favicon.ico et déclinaisons PNG transparentes (512x512)"
    ],
    applicantsCount: 7,
    createdAt: 'Il y a 1h',
  },
  {
    id: 'tsk_103',
    title: "Recherche et qualification de 50 prospects B2B SaaS (LinkedIn + Emails)",
    description: "Collecter 50 contacts ciblés : Directeurs Marketing ou Growth de scale-ups e-commerce en France (> 20 salariés). Colonnes requises : Prénom, Nom, Poste exact, Entreprise, Profil LinkedIn, Email professionnel vérifié.",
    category: 'assistance',
    status: 'OPEN',
    reward: 32.00,
    platformFee: 3.50,
    totalBudget: 35.50,
    timeLimitHours: 12,
    minLevelRequired: 1,
    clientId: 'cli_03',
    clientName: 'GrowthLab Agency',
    clientAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    clientRating: 4.8,
    clientHireRate: 92,
    requiredProofs: [
      "Fichier Google Sheets ou CSV partagé avec 50 lignes complètes",
      "Rapport de bounce rate vérifié (NeverBounce ou Dropcontact)"
    ],
    applicantsCount: 5,
    createdAt: 'Il y a 2h',
  },
  {
    id: 'tsk_104',
    title: "Traduction & adaptation SEO Anglais -> Français pour 4 fiches produits",
    description: "Traduction humaine de 4 pages de descriptions d'accessoires high-tech (environ 1 200 mots au total). Respect du ton de marque premium et intégration naturelle des mots-clés fournis.",
    category: 'copywriting',
    status: 'IN_PROGRESS',
    reward: 28.00,
    platformFee: 3.00,
    totalBudget: 31.00,
    timeLimitHours: 6,
    minLevelRequired: 1,
    clientId: 'cli_04',
    clientName: 'ÉlectroShop Direct',
    clientAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    clientRating: 4.7,
    clientHireRate: 89,
    requiredProofs: [
      "Document Google Docs avec mode suggestion et texte final relu",
      "Tableau récapitulatif des métadescriptions optimisées"
    ],
    applicantsCount: 4,
    assignedToId: 'usr_me_1',
    assignedToName: 'Aero Mehdi',
    assignedAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    createdAt: 'Il y a 3h',
  },
  {
    id: 'tsk_105',
    title: "Test utilisateur UX (Application mobile iOS) + Rapport d'évaluation",
    description: "Télécharger notre application TestFlight, effectuer un parcours d'inscription complet et d'achat simulé, et rédiger un retour clair sur les éventuels points de friction rencontrés.",
    category: 'micro',
    status: 'OPEN',
    reward: 18.00,
    platformFee: 2.00,
    totalBudget: 20.00,
    timeLimitHours: 2,
    minLevelRequired: 1,
    clientId: 'cli_05',
    clientName: 'Nox Fintech',
    clientAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    clientRating: 4.9,
    clientHireRate: 95,
    requiredProofs: [
      "3 captures d'écran des étapes clés",
      "Rapport écrit structuré de 200 mots minimum décrivant l'expérience"
    ],
    applicantsCount: 12,
    createdAt: 'Il y a 10 min',
  },
  {
    id: 'tsk_106',
    title: "Détourage propre et ombrage réaliste de 12 photos de mobilier",
    description: "Photos de chaises et canapés sur fond d'atelier à détourer à la plume (pas de détourage automatique flou) et exporter sur fond blanc pur (RGB 255,255,255) avec ombre portée naturelle.",
    category: 'design',
    status: 'OPEN',
    reward: 35.00,
    platformFee: 3.50,
    totalBudget: 38.50,
    timeLimitHours: 8,
    minLevelRequired: 1,
    clientId: 'cli_06',
    clientName: 'Mobilier & Co',
    clientAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
    clientRating: 4.85,
    clientHireRate: 94,
    requiredProofs: [
      "Archive ZIP contenant les 12 fichiers PNG et PSD avec calques conservés"
    ],
    applicantsCount: 6,
    createdAt: 'Il y a 4h',
  }
];

export const initialTransactions: WalletTransaction[] = [
  {
    id: 'tx_901',
    userId: 'usr_me_1',
    type: 'ESCROW_RELEASE',
    amount: 55.00,
    currency: 'EUR',
    description: 'Paiement reçu pour tâche #tsk_089 "Intégration Stripe Checkout"',
    createdAt: 'Hier à 18:20',
    status: 'COMPLETED',
  },
  {
    id: 'tx_902',
    userId: 'usr_me_1',
    type: 'DEPOSIT',
    amount: 100.00,
    currency: 'EUR',
    description: 'Approvisionnement sécurisé par Carte Bancaire',
    createdAt: '25 Sep 2024',
    status: 'COMPLETED',
  },
  {
    id: 'tx_903',
    userId: 'usr_me_1',
    type: 'ESCROW_LOCK',
    amount: -50.00,
    currency: 'EUR',
    description: 'Séquestre bloqué pour publication tâche #tsk_101',
    createdAt: '24 Sep 2024',
    status: 'COMPLETED',
  },
  {
    id: 'tx_904',
    userId: 'usr_me_1',
    type: 'COMMISSION',
    amount: -8.25,
    currency: 'EUR',
    description: 'Commission de service plateforme Tâches (Niveau 3 - 15%)',
    createdAt: 'Hier à 18:20',
    status: 'COMPLETED',
  }
];
