import { Locale } from './i18n/types';

export interface TaskExample {
  id: number;
  orderNumber: number;
  category: 'development' | 'design' | 'marketing' | 'copywriting' | 'assistance' | 'micro';
  categoryLabel: Record<Locale, string>;
  title: Record<Locale, string>;
  description: Record<Locale, string>;
  priceDH: number;
  turnaroundTime: string;
  city?: string;
  completedDate: string;
  executor: {
    name: string;
    avatar: string;
    role: Record<Locale, string>;
    rating: number;
    completedCount: number;
    badge: Record<Locale, string>;
  };
  clientReview?: {
    author: string;
    rating: number;
    comment: Record<Locale, string>;
  };
  deliverables: string[];
  tags: string[];
  searchIntentKeywords: string[];
}

export const POPULAR_SEARCH_INTENTS = [
  { id: 'youcan', label: '🛍️ YouCan / Shopify COD', query: 'youcan' },
  { id: 'logo', label: '🎨 Logo & Charte', query: 'logo' },
  { id: 'traduction', label: '✍️ Traduction Arabe/Français', query: 'traduction' },
  { id: 'excel', label: '📊 Saisie Factures Excel', query: 'excel' },
  { id: 'reels', label: '🎬 Montage TikTok & Reels', query: 'reels' },
  { id: 'voixoff', label: '🎙️ Voix off Darija', query: 'voix off' },
  { id: 'demarches', label: '📍 Dépôt & Démarches Terrain', query: 'dépôt' },
  { id: 'whatsapp', label: '📱 Service Client WhatsApp', query: 'whatsapp' },
  { id: 'retouche', label: '📸 Détourage Photos E-com', query: 'détourage' },
  { id: 'cmi', label: '💳 Paiement CMI Bancaire', query: 'cmi' },
];

export const TASK_EXAMPLES: TaskExample[] = [
  {
    id: 1001,
    orderNumber: 2498101,
    category: 'design',
    categoryLabel: {
      fr: 'Graphisme & Design',
      ar: 'تصميم وجرافيك',
      en: 'Graphics & Design',
      ru: 'Дизайн и графика',
      es: 'Diseño y gráficos',
    },
    title: {
      fr: 'Création d’un logo moderne et bannières réseaux sociaux pour marque de vêtements',
      ar: 'تصميم شعار عصري وبانرات إعلانية لعلامة ملابس على إنستغرام',
      en: 'Modern logo design & social media banners for fashion clothing brand',
      ru: 'Разработка логотипа и баннеров для бренда одежды в соцсетях',
      es: 'Diseño de logo moderno y banners para marca de ropa en redes sociales',
    },
    description: {
      fr: "Création d'un logo épuré (3 propositions) avec charte graphique (codes couleurs, typographies) et déclinaison en 4 bannières pour Instagram et Facebook. Mise en avant de l'esprit streetwear moderne marocain. Fichiers vectoriels AI, PNG fond transparent et maquettes HD fournies.",
      ar: "تصميم لوجو احترافي عصري (3 مقترحات) مع دليل الهوية البصرية وألوان وخطوط الماركة، مع 4 تصاميم لصفحات إنستغرام وفيسبوك. تسليم الملفات المفتوحة بصيغ AI و PNG بدقة عالية جاهزة للاستخدام.",
      en: "Design of a clean modern logo (3 initial concepts) with brand style guide (colors, typography) and 4 promotional banners for Instagram and Facebook. Vector AI, transparent PNG, and high-res mockups delivered.",
      ru: "Создание стильного логотипа (3 варианта) и комплекта баннеров для Instagram и Facebook. Исходники в векторе AI, прозрачный PNG и шрифты.",
      es: "Diseño de logo moderno (3 propuestas) y 4 banners para Instagram/Facebook con archivos vectoriales AI y PNG transparente.",
    },
    priceDH: 250,
    turnaroundTime: '24h',
    city: 'Casablanca',
    completedDate: '2026-09-28',
    executor: {
      name: 'Yassine M.',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
      role: {
        fr: 'Graphiste & Designer UI',
        ar: 'مصمم جرافيك وهويات بصرية',
        en: 'Graphic & UI Designer',
        ru: 'Графический дизайнер',
        es: 'Diseñador Gráfico',
      },
      rating: 4.9,
      completedCount: 64,
      badge: {
        fr: 'Prestataire vérifié ⭐',
        ar: 'منفذ معتمد ⭐',
        en: 'Verified Pro ⭐',
        ru: 'Проверенный исполнитель ⭐',
        es: 'Profesional verificado ⭐',
      },
    },
    clientReview: {
      author: 'Karim (Boutique Mode Casablanca)',
      rating: 5,
      comment: {
        fr: 'Travail impeccable, livré en moins de 24h avec les fichiers sources modifiables. Je recommande vivement Yassine !',
        ar: 'عمل متقن وسريع جداً في أقل من 24 ساعة مع تسليم الملفات المفتوحة. أنصح بالتعامل معه بشدة!',
        en: 'Flawless work delivered in under 24 hours with editable source files. Highly recommended!',
        ru: 'Отличный исполнитель! Все выполнил качественно, быстро и без лишних вопросов. Рекомендую.',
        es: '¡Trabajo impecable entregado en menos de 24 horas con archivos editables! Muy recomendado.',
      },
    },
    deliverables: ['Fichiers vectoriels modifiables (.AI, .EPS, .SVG)', 'Logo en PNG transparent Haute Définition', '4 visuels réseaux sociaux (1080x1080 et 1080x1920)'],
    tags: ['Logo', 'Canva', 'Photoshop', 'Instagram', 'Bannière', 'Branding'],
    searchIntentKeywords: ['logo', 'créer logo', 'تصميم لوجو', 'شعار', 'design logo', 'charte graphique', 'bannière instagram', 'marque vetement', 'identity', 'vecteur'],
  },
  {
    id: 1002,
    orderNumber: 2498102,
    category: 'development',
    categoryLabel: {
      fr: 'Web & E-commerce',
      ar: 'برمجة ومتاجر إلكترونية',
      en: 'Web & E-commerce',
      ru: 'Разработка и IT',
      es: 'Desarrollo web y E-commerce',
    },
    title: {
      fr: 'Configuration complète d’une boutique YouCan Shop / Shopify au Maroc avec COD',
      ar: 'إنشاء وضبط متجر إلكتروني YouCan Shop / Shopify في المغرب مع الدفع عند الاستلام',
      en: 'Full setup of a YouCan Shop / Shopify store in Morocco with fast COD checkout',
      ru: 'Настройка интернет-магазина YouCan / Shopify под ключ для дропшиппинга',
      es: 'Configuración completa de tienda YouCan / Shopify en Marruecos con pago contra entrega',
    },
    description: {
      fr: "Paramétrage complet d'une boutique YouCan Shop spécialisée en cosmétique naturelle : thème responsive, configuration du formulaire de commande express en 1 clic pour le paiement à la livraison (Cash on Delivery), paramétrage des transporteurs et villes marocaines, et intégration des 12 premiers produits avec textes et visuels optimisés.",
      ar: "إعداد متكامل لمتجر YouCan Shop لمنتجات التجميل: تركيب قالب سريع، تفعيل نموذج الطلب السريع والدفع عند الاستلام (COD)، ضبط شركات الشحن ومدن التوصيل في المغرب وإدخال أول 12 منتجاً مع الصور والأوصاف التسويقية.",
      en: "Full setup of a YouCan Shop e-commerce store for natural cosmetics: responsive theme, 1-click Cash on Delivery express checkout form, Moroccan shipping zones configuration, and 12 initial products integration with optimized copy and photos.",
      ru: "Полная настройка магазина на платформе YouCan Shop: быстрая форма заказа с оплатой при получении, зоны доставки по городам и загрузка 12 товаров.",
      es: "Configuración integral de tienda YouCan Shop: formulario rápido contra reembolso (COD), zonas de envío e integración de 12 productos con fotos.",
    },
    priceDH: 550,
    turnaroundTime: '48h',
    city: 'En ligne',
    completedDate: '2026-09-27',
    executor: {
      name: 'Mehdi B.',
      avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120&auto=format&fit=crop&q=80',
      role: {
        fr: 'Développeur E-commerce & YouCan',
        ar: 'مطور متاجر إلكترونية ويوكان',
        en: 'E-commerce & YouCan Developer',
        ru: 'Веб-разработчик',
        es: 'Desarrollador Web y E-commerce',
      },
      rating: 5.0,
      completedCount: 92,
      badge: {
        fr: 'Top Prestataire ⭐',
        ar: 'أفضل منفذ ⭐',
        en: 'Top Rated Pro ⭐',
        ru: 'Топ исполнитель ⭐',
        es: 'Mejor profesional ⭐',
      },
    },
    clientReview: {
      author: 'Sara (Boutique Bio Rabat)',
      rating: 5,
      comment: {
        fr: 'Mehdi a configuré la boutique en 48h chrono, tout fonctionne parfaitement pour les commandes COD. Merci beaucoup !',
        ar: 'مهدي أنجز المتجر في 48 ساعة فقط وباحترافية عالية، وتجربة الشراء سلسة جداً. شكراً جزيلاً!',
        en: 'Mehdi set up the store in 48 hours, everything works smoothly with COD orders. Super satisfied!',
        ru: 'Очень довольна результатом! Магазин работает идеально, заказ оформляется в один клик. Спасибо!',
        es: 'Mehdi configuró la tienda en 48 horas, todo funciona perfecto con pedidos contra reembolso.',
      },
    },
    deliverables: ['Boutique YouCan / Shopify 100% fonctionnelle', 'Formulaire commande express COD activé', '12 fiches produits publiées avec photos', 'Guide vidéo pour gérer les commandes'],
    tags: ['YouCan', 'Shopify', 'E-commerce', 'COD', 'Maroc', 'Paiement à la livraison'],
    searchIntentKeywords: ['youcan', 'youcan shop', 'shopify', 'متجر يوكان', 'متجر الكتروني', 'cod', 'cash on delivery', 'الدفع عند الاستلام', 'boutique en ligne', 'e-commerce maroc', 'creer boutique'],
  },
  {
    id: 1003,
    orderNumber: 2498103,
    category: 'copywriting',
    categoryLabel: {
      fr: 'Traduction & Rédaction',
      ar: 'ترجمة وكتابة محتوى',
      en: 'Translation & Copywriting',
      ru: 'Тексты и переводы',
      es: 'Traducción y redacción',
    },
    title: {
      fr: 'Traduction assermentée d’un contrat commercial et statuts d’entreprise Arabe ⇄ Français',
      ar: 'ترجمة عقد تجاري وقانوني من العربية إلى الفرنسية (4 صفحات)',
      en: 'Certified commercial contract & company bylaws translation Arabic ⇄ French',
      ru: 'Перевод коммерческого договора и устава компании с арабского на французский',
      es: 'Traducción jurada de contrato comercial y estatutos societarios Árabe ⇄ Francés',
    },
    description: {
      fr: "Traduction rigoureuse et fidèle d'un contrat de distribution commerciale et de statuts de société (4 pages, ~1600 mots). Respect strict de la terminologie juridique marocaine (Code de Commerce et DOC), mise en page identique au document d'origine sous format Word modifiable et PDF prêt à la signature.",
      ar: "ترجمة دقيقة ومحكمة لعقد توزيع تجاري والنظام الأساسي لشركة (4 صفحات، ~1600 كلمة). الالتزام التام بالمصطلحات القانونية المغربية المعمول بها مع الحفاظ على نفس التنسيق الأصلي بصيغتي Word و PDF.",
      en: "Precise translation of a 4-page commercial distribution agreement and corporate bylaws (~1,600 words). Strict conformity with Moroccan legal terminology, delivered in formatted Word and signature-ready PDF.",
      ru: "Качественный юридический перевод договора дистрибуции на 4 страницы. Соблюдение юридической терминологии и сохранение оригинального форматирования.",
      es: "Traducción rigurosa de contrato de distribución de 4 páginas (~1600 palabras) respetando terminología jurídica marroquí y formato original.",
    },
    priceDH: 220,
    turnaroundTime: '24h',
    city: 'Rabat',
    completedDate: '2026-09-26',
    executor: {
      name: 'Fatima-Zahra E.',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
      role: {
        fr: 'Traductrice assermentée & Juriste',
        ar: 'مترجمة معتمدة ومختصة قانونية',
        en: 'Certified Legal Translator',
        ru: 'Профессиональный переводчик',
        es: 'Traductora jurada',
      },
      rating: 4.95,
      completedCount: 118,
      badge: {
        fr: 'Experte Certifiée ⭐',
        ar: 'خبيرة معتمدة ⭐',
        en: 'Certified Expert ⭐',
        ru: 'Сертифицированный эксперт ⭐',
        es: 'Experta certificada ⭐',
      },
    },
    clientReview: {
      author: 'Amine (Cabinet Conseil Tanger)',
      rating: 5,
      comment: {
        fr: 'Traduction d’une grande précision juridique, livrée avant l’échéance prévue. Service exemplaire.',
        ar: 'ترجمة في غاية الدقة والاحترافية، مع الالتزام التام بالموعد المحدد. خدمة ممتازة جداً.',
        en: 'High quality legal precision delivered before the deadline. Exemplary service!',
        ru: 'Очень точный и грамотный перевод. Работа выполнена раньше срока. Спасибо!',
        es: 'Traducción de gran precisión jurídica entregada antes del plazo. Servicio ejemplar.',
      },
    },
    deliverables: ['Document traduit au format Word (.docx) avec mise en page conservée', 'Version PDF propre prête à l’impression'],
    tags: ['Traduction', 'Arabe', 'Français', 'Contrat', 'Juridique', 'Statuts'],
    searchIntentKeywords: ['traduction', 'traduire contrat', 'ترجمة', 'ترجمة عربية فرنسية', 'ترجمة عقود', 'arabe francais', 'juridique', 'statuts sarl', 'assermentee', 'translation'],
  },
  {
    id: 1004,
    orderNumber: 2498104,
    category: 'marketing',
    categoryLabel: {
      fr: 'Marketing & Vidéo',
      ar: 'تسويق ومونتاج فيديو',
      en: 'Marketing & Video',
      ru: 'Маркетинг и видео',
      es: 'Marketing y vídeo',
    },
    title: {
      fr: 'Montage dynamique de 4 vidéos TikTok / Instagram Reels avec sous-titres animés en Darija/Français',
      ar: 'مونتاج احترافي لـ 4 مقاطع تيك توك وريلز مع نصوص متحركة بالدارجة والفرنسية',
      en: 'Dynamic video editing of 4 TikTok / Reels with animated captions in Darija/French',
      ru: 'Монтаж 4 динамичных Reels / TikTok с анимированными субтитрами',
      es: 'Edición dinámica de 4 vídeos TikTok / Reels con subtítulos animados en Darija/Francés',
    },
    description: {
      fr: "Montage rythmé de 4 vidéos verticales (format 9:16, 30 à 45 sec) à partir de vidéos brutes smartphone : découpage dynamique, ajout de sous-titres animés avec mots en gras et couleurs (style Alex Hormozi) en Darija et Français, effets sonores (SFX), zooms et musiques tendances libres de droits.",
      ar: "مونتاج 4 مقاطع فيديو عمودية (9:16) مدتها بين 30 و 45 ثانية: تقطيع ديناميكي، نصوص ملونة ومتحركة بالدارجة والفرنسية بنمط هورموزي، مؤثرات صوتية وموسيقى حماسية لزيادة التفاعل والمشاهدات.",
      en: "Editing of 4 vertical videos (9:16, 30-45s each) from raw footage: fast-paced cuts, animated Hormozi-style captions in French/Darija, trending sound FX, and retention zooms.",
      ru: "Монтаж 4 вертикальных видео 9:16 по 30-45 сек: динамичная нарезка, анимированные субтитры, звуковые эффекты и трендовая музыка.",
      es: "Montaje de 4 vídeos verticales (9:16) de 30-45 segundos: cortes dinámicos, subtítulos animados estilo Hormozi, efectos sonoros y música en tendencia.",
    },
    priceDH: 280,
    turnaroundTime: '24h',
    city: 'Marrakech',
    completedDate: '2026-09-25',
    executor: {
      name: 'Othmane B.',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
      role: {
        fr: 'Monteur Vidéo & Spécialiste Shorts/Reels',
        ar: 'مونتير فيديو وصانع محتوى ريلز',
        en: 'Video Editor & Reels Specialist',
        ru: 'Видеомонтажер',
        es: 'Editor de Vídeo',
      },
      rating: 4.88,
      completedCount: 53,
      badge: {
        fr: 'Créateur Pro ⭐',
        ar: 'مبدع محترف ⭐',
        en: 'Pro Creator ⭐',
        ru: 'Профи креативщик ⭐',
        es: 'Creador Pro ⭐',
      },
    },
    clientReview: {
      author: 'Nadia (Marrakech Fashion)',
      rating: 5,
      comment: {
        fr: 'Les vidéos ont fait un carton sur notre compte Instagram ! Rythme parfait et sous-titres très propres.',
        ar: 'الفيديوهات حققت تفاعلاً ممتازاً على صفحتنا في إنستغرام! مونتاج عصري ومتقن.',
        en: 'The videos performed amazingly on our Instagram account! Great pacing and crisp captions.',
        ru: 'Ролики получились очень бодрыми, субтитры сделаны отлично. Обязательно обращусь снова!',
        es: '¡Los vídeos tuvieron un éxito enorme en Instagram! Ritmo perfecto y subtítulos impecables.',
      },
    },
    deliverables: ['4 fichiers vidéos MP4 Full HD (1080x1920)', 'Sous-titres animés synchronisés', 'Fichiers projets CapCut / Premiere'],
    tags: ['Reels', 'TikTok', 'CapCut', 'Premiere Pro', 'Sous-titres', 'Montage'],
    searchIntentKeywords: ['montage video', 'reels', 'tiktok', 'مونتاج فيديو', 'ريلز', 'تيك توك', 'sous titres', 'video tiktok', 'capcut', 'video editor', 'hormozi'],
  },
  {
    id: 1005,
    orderNumber: 2498105,
    category: 'assistance',
    categoryLabel: {
      fr: 'Saisie & Administratif',
      ar: 'إدخال بيانات وسكرتارية',
      en: 'Data Entry & Assistance',
      ru: 'Ввод данных и ассистент',
      es: 'Entrada de datos y asistencia',
    },
    title: {
      fr: 'Saisie et réconciliation de 250 factures d’achats et ventes sous Excel avec formules TVA',
      ar: 'إدخال وتدقيق 250 فاتورة شراء ومبيعات في جدول Excel مع حساب الضريبة TVA',
      en: 'Data entry & reconciliation of 250 purchase invoices in Excel with VAT formulas',
      ru: 'Ввод и сверка 250 счетов-фактур в таблицу Excel с расчетом НДС',
      es: 'Entrada y conciliación de 250 facturas de compra en Excel con cálculo de IVA',
    },
    description: {
      fr: "Saisie détaillée de 250 factures scannées (fournisseur, date, numéro de facture, montant HT, taux de TVA marocaine 20%/14%/10%, montant TTC, mode de règlement) avec formules automatiques de contrôle et détection des doublons. Fichier propre et prêt pour le comptable.",
      ar: "إدخال تفصيلي لـ 250 فاتورة ممسوحة ضوئياً (اسم المورد، التاريخ، رقم الفاتورة، المبلغ الصافي، الضريبة على القيمة المضافة، المبلغ الإجمالي) مع معادلات تدقيق تلقائية والتأكد من عدم وجود تكرار.",
      en: "Detailed entry of 250 scanned invoices (supplier, date, invoice number, subtotal, Moroccan VAT rates, grand total, payment method) with automated cross-check formulas and duplicate detection.",
      ru: "Ввод данных из 250 отсканированных счетов в Excel шаблон: проверка сумм, расчет НДС и проверка на дубликаты. Готово для бухгалтера.",
      es: "Registro detallado de 250 facturas escaneadas en Excel con fórmulas de verificación automática de importes e IVA.",
    },
    priceDH: 180,
    turnaroundTime: '24h',
    city: 'Fès',
    completedDate: '2026-09-24',
    executor: {
      name: 'Salma L.',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
      role: {
        fr: 'Assistante Virtuelle & Experte Excel',
        ar: 'مساعدة افتراضية وخبيرة إكسيل',
        en: 'Virtual Assistant & Excel Expert',
        ru: 'Виртуальный ассистент',
        es: 'Asistente virtual y experta Excel',
      },
      rating: 4.98,
      completedCount: 140,
      badge: {
        fr: 'Top Rigueur ⭐',
        ar: 'دقة فائقة ⭐',
        en: 'Top Precision ⭐',
        ru: 'Высокая точность ⭐',
        es: 'Máxima precisión ⭐',
      },
    },
    clientReview: {
      author: 'Reda (Société Commerciale Fès)',
      rating: 5,
      comment: {
        fr: 'Salma est d’une rigueur impressionnante. Zéro faute de frappe, tableau très bien organisé avec formules.',
        ar: 'سلمى دقيقة للغاية ومنظمة. لا يوجد أي خطأ في الأرقام مع تنظيم رائع للجداول والمعادلات.',
        en: 'Salma is extremely thorough. Zero typos, well structured table with working formulas.',
        ru: 'Прекрасная работа! Все данные сверены до копейки, формулы работают. Очень помогла.',
        es: 'Salma es muy rigurosa. Cero errores, tabla muy bien estructurada con fórmulas.',
      },
    },
    deliverables: ['Fichier Excel .xlsx complet et vérifié', 'Rapprochement des montants HT / TVA / TTC', 'Zéro doublon de factures'],
    tags: ['Excel', 'Google Sheets', 'Factures', 'Comptabilité', 'Saisie', 'TVA'],
    searchIntentKeywords: ['excel', 'saisie excel', 'saisie factures', 'ادخال بيانات', 'اكسيل', 'فواتير', 'comptabilite', 'tva maroc', 'data entry', 'sheets', 'tableau'],
  },
  {
    id: 1006,
    orderNumber: 2498106,
    category: 'micro',
    categoryLabel: {
      fr: 'Services terrain & Micro-tâches',
      ar: 'مهام ميدانية وخدمات سريعة',
      en: 'Field Errands & Micro-tasks',
      ru: 'Микро-задачи и поручения',
      es: 'Recados y microtareas',
    },
    title: {
      fr: 'Dépôt physique urgent de dossier à la Conservation Foncière / Tribunal à Rabat',
      ar: 'إيداع ملف رسمي بمكتب الضبط وأخذ وصل الإيداع في الرباط',
      en: 'Urgent physical delivery of legal files to Land Registry / Court in Rabat',
      ru: 'Курьерская доставка документов с отметкой о вручении в Рабате',
      es: 'Entrega física urgente de expediente en Registro / Juzgado de Rabat',
    },
    description: {
      fr: "Récupération d'un pli scellé auprès d'une agence au centre-ville de Rabat et dépôt officiel au bureau d'ordre d'une administration publique avec obtention du récépissé tamponné et daté. Envoi immédiat d'une photo haute résolution du tampon puis renvoi du document original par courrier express.",
      ar: "استلام ظرف مختوم من وكالة وسط مدينة الرباط وإيداعه رسمياً بمكتب الضبط بإحدى الإدارات العمومية والحصول على وصل إيداع مؤرخ ومختوم، مع إرسال صورة واضحة فورية لوصل الاستلام.",
      en: "Pickup of a sealed package from an office in Rabat center and official submission to a ministry registry with a stamped, dated receipt acknowledgment. Immediate high-res photo sent upon delivery.",
      ru: "Забрать конверт в центре Рабата, отвезти в ведомство и получить штамп на входящий документ с датой. Прислать фото расписки.",
      es: "Recogida de sobre cerrado en Rabat centro y entrega oficial en registro público con sello oficial fechado y envío inmediato de fotografía.",
    },
    priceDH: 150,
    turnaroundTime: '6h',
    city: 'Rabat',
    completedDate: '2026-09-24',
    executor: {
      name: 'Tariq A.',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
      role: {
        fr: 'Prestataire terrain & Démarches',
        ar: 'منفذ مهام ميدانية وإدارية',
        en: 'Field Agent & Errands',
        ru: 'Исполнитель поручений',
        es: 'Agente de campo y gestiones',
      },
      rating: 4.92,
      completedCount: 77,
      badge: {
        fr: 'Vérifié Local ⭐',
        ar: 'معتمد محلياً ⭐',
        en: 'Verified Local ⭐',
        ru: 'Локальный исполнитель ⭐',
        es: 'Verificado local ⭐',
      },
    },
    clientReview: {
      author: 'Cabinet Juridique (Casablanca)',
      rating: 5,
      comment: {
        fr: 'Tariq nous a fait gagner un temps précieux. Dépôt effectué dans l’heure avec photo nette du tampon. Parfait !',
        ar: 'طارق وفر علينا وقتاً ثميناً. تم إيداع الملف بسرعة مع إرسال صورة واضحة للختم. ممتاز جداً!',
        en: 'Tariq saved us precious time. Delivery completed within an hour with crisp photo of stamp.',
        ru: 'Оперативно выполнил поручение, через час уже прислал фото штампа канцелярии. Спасибо!',
        es: 'Tariq nos ahorró mucho tiempo. Entrega rápida con foto clara del sello.',
      },
    },
    deliverables: ['Photo nette de l’accusé de réception tamponné et daté', 'Confirmation immédiate par WhatsApp', 'Expédition de l’original par CTM/Amana'],
    tags: ['Rabat', 'Démarches', 'Bureau d’ordre', 'Terrain', 'Urgent', 'Tribunal'],
    searchIntentKeywords: ['depot rabat', 'demarches administratives', 'خدمات ادارية', 'ايداع وثائق', 'الرباط', 'bureau dordre', 'conservation fonciere', 'coursier express', 'recapitulatif'],
  },
  {
    id: 1007,
    orderNumber: 2498107,
    category: 'marketing',
    categoryLabel: {
      fr: 'Marketing & Vidéo',
      ar: 'تسويق ومونتاج فيديو',
      en: 'Marketing & Video',
      ru: 'Маркетинг и видео',
      es: 'Marketing y vídeo',
    },
    title: {
      fr: 'Enregistrement voix-off féminine en Darija marocaine pour spot publicitaire radio/TikTok (1 min)',
      ar: 'تسجيل صوتي نسائي احترافي (فويس أوفر) بالدارجة المغربية لإعلان تجاري (دقيقة واحدة)',
      en: 'Professional female voiceover in Moroccan Darija for radio/TikTok ad (1 min)',
      ru: 'Женская озвучка на марокканском диалекте для радио и TikTok рекламы',
      es: 'Locución femenina profesional en Darija marroquí para spot de radio/TikTok (1 min)',
    },
    description: {
      fr: "Enregistrement en studio d'une voix-off dynamique, chaleureuse et vendeuse en Darija marocaine (durée 60 secondes) pour une campagne de promotion de cosmétique bio. Livraison d'un fichier audio WAV masterisé sans bruit de fond, avec 2 variantes d'intonations (ton énergique et ton doux).",
      ar: "تسجيل صوتي احترافي بجودة استوديو عالية بالدارجة المغربية بنبرة صوت دافئة ومقنعة (المدة 60 ثانية) لإعلان ترويجي لمنتجات تجميلية. تسليم بصيغة WAV نقية مع خيارين لنبرة الإلقاء.",
      en: "Studio-recorded dynamic and engaging female voiceover in Moroccan Darija (60s) for an organic cosmetics campaign. Clean mastered WAV file delivered with 2 tone variations.",
      ru: "Запись женской дикторской озвучки на студийном оборудовании: чистый звук WAV без шумов, две интонации на выбор.",
      es: "Grabación de locución femenina en estudio en Darija marroquí (60s) para spot publicitario. Audio WAV masterizado.",
    },
    priceDH: 200,
    turnaroundTime: '12h',
    city: 'Casablanca',
    completedDate: '2026-09-23',
    executor: {
      name: 'Ghita N.',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
      role: {
        fr: 'Voix-off & Comédienne',
        ar: 'معلقة صوتية وممثلة دبلجة',
        en: 'Voiceover Artist & Actress',
        ru: 'Диктор и актер озвучки',
        es: 'Locutora profesional',
      },
      rating: 4.97,
      completedCount: 61,
      badge: {
        fr: 'Voix Gold ⭐',
        ar: 'صوت ذهبي ⭐',
        en: 'Gold Voice ⭐',
        ru: 'Золотой голос ⭐',
        es: 'Voz Gold ⭐',
      },
    },
    clientReview: {
      author: 'Agence Digitale (Casablanca)',
      rating: 5,
      comment: {
        fr: 'Une voix captivante avec une diction parfaite en Darija. Le rendu final colle exactement à nos attentes.',
        ar: 'صوت رائع ونطق سليم ومؤثر بالدارجة المغربية. النتيجة النهائية مطابقة تماماً لتطلعاتنا.',
        en: 'Captivating voice with flawless Darija pronunciation. The result matched our brief 100%.',
        ru: 'Превосходная дикция и потрясающий тембр! Звук чистый, без эха и шумов. Спасибо!',
        es: 'Voz cautivadora con dicción perfecta en Darija. El resultado superó nuestras expectativas.',
      },
    },
    deliverables: ['Fichier audio WAV Haute Qualité 24bit/48kHz', 'Version MP3 légère optimisée', '2 prises d’intonations différentes'],
    tags: ['Voix off', 'Darija', 'Podcast', 'Publicité', 'Audio', 'Studio'],
    searchIntentKeywords: ['voix off', 'voix off darija', 'فويس اوفر', 'تسجيل صوتي', 'تعليق صوتي', 'voice over maroc', 'darija marocaine', 'pub radio', 'voix pub'],
  },
  {
    id: 1008,
    orderNumber: 2498108,
    category: 'development',
    categoryLabel: {
      fr: 'Web & E-commerce',
      ar: 'برمجة ومتاجر إلكترونية',
      en: 'Web & E-commerce',
      ru: 'Разработка и IT',
      es: 'Desarrollo web y E-commerce',
    },
    title: {
      fr: 'Intégration et validation du module de paiement en ligne CMI sur WordPress / WooCommerce',
      ar: 'ربط وتفعيل بوابة الدفع بالبطاقات البنكية CMI على ووردبريس وووكومرس',
      en: 'CMI Moroccan bank card payment gateway integration on WordPress / WooCommerce',
      ru: 'Подключение и настройка платежного шлюза CMI для приема карт в Марокко',
      es: 'Integración y validación de pasarela de pago bancario CMI en WordPress / WooCommerce',
    },
    description: {
      fr: "Installation et configuration complète de la passerelle de paiement CMI (Centre Monétique Interbancaire) sur une boutique WooCommerce : paramétrage des clés marchand et certificats SHA, tests complets des transactions bancaires en mode Sandbox, et passage en production avec paiement réel par carte bancaire marocaine et internationale.",
      ar: "تثبيت وضبط إضافة الدفع الإلكتروني الرسمية CMI (مركز النقديات المغربي) على متجر WooCommerce: إدخال مفاتيح التشفير، إجراء الاختبارات بنجاح وتفعيل الدفع الحقيقي بالبطاقات البنكية المحلية والدولية.",
      en: "Full installation and configuration of the official CMI payment gateway on WooCommerce: merchant keys & SHA hash config, sandbox test runs, and live production deployment for Moroccan and international credit cards.",
      ru: "Установка и настройка платежного шлюза CMI на WooCommerce: тестирование в песочнице и перевод в боевой режим для приема карт.",
      es: "Configuración completa del módulo de pago CMI en WooCommerce: pruebas sandbox y activación en producción con tarjetas bancarias.",
    },
    priceDH: 450,
    turnaroundTime: '24h',
    city: 'Casablanca',
    completedDate: '2026-09-22',
    executor: {
      name: 'Zakaria T.',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80',
      role: {
        fr: 'Développeur Backend & Intégrateur CMI',
        ar: 'مطور واجهات خلفية وبوابات دفع',
        en: 'Backend Developer & Payment Integrator',
        ru: 'Backend разработчик',
        es: 'Desarrollador Backend',
      },
      rating: 5.0,
      completedCount: 83,
      badge: {
        fr: 'Paiement Sécurisé ⭐',
        ar: 'معتمد في الدفع ⭐',
        en: 'Secure Payment Pro ⭐',
        ru: 'Специалист по платежам ⭐',
        es: 'Experto en pagos ⭐',
      },
    },
    clientReview: {
      author: 'Mode Maroc (Casablanca)',
      rating: 5,
      comment: {
        fr: 'Zakaria maîtrise parfaitement la procédure CMI. L’intégration s’est faite sans accroc en 24h.',
        ar: 'زكرياء متمكن جداً من بروتوكول CMI، وتم تفعيل الدفع البنكي بدون أي مشاكل في 24 ساعة.',
        en: 'Zakaria mastered the CMI procedure. The integration went smoothly in under 24 hours.',
        ru: 'Отличный спец по платежкам! Все подключил, проверил, деньги списываются и зачисляются четко.',
        es: 'Zakaria domina perfectamente la pasarela CMI. Integración sin fallos en 24h.',
      },
    },
    deliverables: ['Module CMI installé et configuré', 'Tests de validation Sandbox réussis', 'Paiements réels par carte bancaire fonctionnels'],
    tags: ['CMI', 'WooCommerce', 'WordPress', 'Paiement en ligne', 'Carte bancaire'],
    searchIntentKeywords: ['cmi', 'paiement cmi', 'دفع الكتروني', 'cmi maroc', 'woocommerce cmi', 'carte bancaire maroc', 'centre monetique interbancaire', 'passerelle paiement', 'paiement en ligne'],
  },
  {
    id: 1009,
    orderNumber: 2498109,
    category: 'assistance',
    categoryLabel: {
      fr: 'Saisie & Administratif',
      ar: 'إدخال بيانات وسكرتارية',
      en: 'Data Entry & Assistance',
      ru: 'Ввод данных и ассистент',
      es: 'Entrada de datos y asistencia',
    },
    title: {
      fr: 'Gestion du service client WhatsApp Business et confirmation de commandes COD pendant 5 jours',
      ar: 'إدارة خدمة الزبائن وتأكيد طلبيات التجارة الإلكترونية عبر واتساب لمدة 5 أيام',
      en: 'WhatsApp Business customer support & order confirmations for 5 days',
      ru: 'Поддержка клиентов в WhatsApp и подтверждение заказов интернет-магазина',
      es: 'Gestión de atención al cliente en WhatsApp Business y confirmación de pedidos',
    },
    description: {
      fr: "Gestion active des messages WhatsApp entrants de 9h à 19h pendant 5 jours pour une boutique e-commerce marocaine : réponses courtoises et rapides en Darija et Français, confirmations d'adresses pour les expéditions COD, traitement des retours et reporting quotidien sur tableur Google Sheets.",
      ar: "متابعة رسائل الزبائن على واتساب للأعمال يومياً من 9 صباحاً إلى 7 مساءً لمدة 5 أيام: الرد السريع واللبق بالدارجة والفرنسية، الاتصال لتأكيد العناوين للشحن وتحديث جدول الطلبيات على Google Sheets.",
      en: "Dedicated WhatsApp Business support handling from 9am to 7pm over 5 days for a Moroccan e-commerce brand: prompt and polite replies in Darija/French, address validation for COD dispatch, and daily updates on Google Sheets.",
      ru: "Обработка входящих сообщений в WhatsApp с 9:00 до 19:00: вежливые ответы клиентам, подтверждение адресов доставки и ведение учета заказов.",
      es: "Atención al cliente en WhatsApp Business durante 5 días: confirmación de pedidos contra reembolso y registro en Google Sheets.",
    },
    priceDH: 400,
    turnaroundTime: '5 jours',
    city: 'En ligne',
    completedDate: '2026-09-21',
    executor: {
      name: 'Meryem B.',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
      role: {
        fr: 'Gestionnaire Service Client & COD',
        ar: 'مسؤولة خدمة عملاء وتأكيد طلبيات',
        en: 'Customer Success & COD Manager',
        ru: 'Менеджер поддержки клиентов',
        es: 'Gestora de atención al cliente y pedidos',
      },
      rating: 4.99,
      completedCount: 126,
      badge: {
        fr: 'Top Support ⭐',
        ar: 'أفضل دعم زبائن ⭐',
        en: 'Top Support ⭐',
        ru: 'Лучшая поддержка ⭐',
        es: 'Top soporte ⭐',
      },
    },
    clientReview: {
      author: 'Cosmétique Express (Casablanca)',
      rating: 5,
      comment: {
        fr: 'Meryem a assuré un taux de confirmation de 88% sur nos commandes. Extrêmement polie et fiable !',
        ar: 'مريم حققت نسبة تأكيد طلبيات بلغت 88% بأسلوب راقٍ واحترافي مع الزبائن. سنواصل العمل معها بالتأكيد!',
        en: 'Meryem achieved an 88% confirmation rate on our orders. Extremely polite and dependable!',
        ru: 'Процент подтверждения заказов вырос до 88%! Очень ответственная и вежливая девушка.',
        es: 'Meryem logró una tasa de confirmación del 88% en nuestros pedidos. ¡Súper fiable!',
      },
    },
    deliverables: ['Suivi de 100% des messages WhatsApp', 'Taux de confirmation élevé sur tableur partagé', 'Rapport quotidien des ventes et réclamations'],
    tags: ['WhatsApp', 'Service Client', 'Confirmation COD', 'Support', 'E-commerce'],
    searchIntentKeywords: ['whatsapp', 'service client', 'confirmation cod', 'خدمة عملاء', 'واتساب', 'تاكيد طلبيات', 'support client', 'teleconseiller', 'assistance virtuelle'],
  },
  {
    id: 1010,
    orderNumber: 2498110,
    category: 'design',
    categoryLabel: {
      fr: 'Graphisme & Design',
      ar: 'تصميم وجرافيك',
      en: 'Graphics & Design',
      ru: 'Дизайн и графика',
      es: 'Diseño y gráficos',
    },
    title: {
      fr: 'Détourage et retouche sur fond blanc pur de 30 photos de produits (caftans & bijoux)',
      ar: 'تفريغ وتعديل احترافي لـ 30 صورة منتجات (قفطان ومجوهرات) على خلفية بيضاء',
      en: 'Background removal & pure white retouching of 30 product photos (caftans & jewelry)',
      ru: 'Обтравка на белый фон и ретушь 30 фото товаров для каталога',
      es: 'Recorte y retoque en fondo blanco puro de 30 fotos de productos para catálogo',
    },
    description: {
      fr: "Détourage soigné au format carré 1200x1200px de 30 photos d'articles : suppression d'arrière-plan, correction de la luminosité et des couleurs, ajout d'une ombre naturelle portée (drop shadow) pour un rendu haut de gamme sur catalogue e-commerce. Livré en PNG transparent et JPG web.",
      ar: "عزل دقيق لخلفية 30 صورة لمنتجات تقليدية ومجوهرات على خلفية بيضاء نقية: إزالة الشوائب، تعديل الألوان والإضاءة، إضافة ظل طبيعي جذاب وتسليم بصيغتي PNG و JPG.",
      en: "Precise clipping path of 30 product items to 1200x1200px: background removal, color & lighting correction, realistic natural shadow addition for e-commerce catalog. Delivered in transparent PNG and web-optimized JPG.",
      ru: "Качественная обтравка на белый фон 30 фото товаров: удаление фона, цветокоррекция и мягкая тень в PNG и JPG.",
      es: "Recorte cuidado en fondo blanco puro de 30 fotos de productos con sombra natural y entrega en PNG transparente.",
    },
    priceDH: 150,
    turnaroundTime: '12h',
    city: 'Fès',
    completedDate: '2026-09-20',
    executor: {
      name: 'Ayoub Z.',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80',
      role: {
        fr: 'Retoucheur Photo Photoshop',
        ar: 'مصمم ومعدل صور فوتوشوب',
        en: 'Photoshop Retoucher',
        ru: 'Ретушер Photoshop',
        es: 'Retocador fotográfico',
      },
      rating: 4.94,
      completedCount: 95,
      badge: {
        fr: 'Expert Retouche ⭐',
        ar: 'خبير تعديل ⭐',
        en: 'Retouch Pro ⭐',
        ru: 'Профи ретуши ⭐',
        es: 'Pro de retoque ⭐',
      },
    },
    clientReview: {
      author: 'Bijouterie El Fassi (Fès)',
      rating: 5,
      comment: {
        fr: 'Les bijoux ressortent magnifiquement bien sur notre site web. Travail soigné et rendu très propre.',
        ar: 'الصور أصبحت جذابة جداً على متجرنا الإلكتروني. عمل متقن واحترافي لأقصى درجة.',
        en: 'The jewelry looks stunning on our web store. Extremely clean and professional work.',
        ru: 'Украшения на сайте теперь смотрятся дорого и презентабельно. Большое спасибо за скорость!',
        es: 'Las joyas lucen increíbles en nuestra tienda online. Trabajo muy limpio y profesional.',
      },
    },
    deliverables: ['30 photos détourées en PNG fond transparent', '30 photos optimisées sur fond blanc pur (1200x1200px)'],
    tags: ['Photoshop', 'Détourage', 'E-commerce', 'Retouche', 'Produits'],
    searchIntentKeywords: ['detourage', 'retouche photo', 'فوتوشوب', 'تفريغ الصور', 'background removal', 'fond blanc', 'photos produits', 'catalogue e-commerce'],
  },
  {
    id: 1011,
    orderNumber: 2498111,
    category: 'marketing',
    categoryLabel: {
      fr: 'Marketing & Vidéo',
      ar: 'تسويق ومونتاج فيديو',
      en: 'Marketing & Video',
      ru: 'Маркетинг и видео',
      es: 'Marketing y vídeo',
    },
    title: {
      fr: 'Paramétrage et optimisation d’une campagne publicitaire TikTok Ads ciblée pour le Maroc',
      ar: 'إعداد وضبط حملة إعلانية ممولة على تيك توك أدز تستهدف المغرب',
      en: 'Setup & targeting of a high-converting TikTok Ads campaign in Morocco',
      ru: 'Настройка таргетированной рекламы TikTok Ads под ключ',
      es: 'Configuración de campaña publicitaria TikTok Ads segmentada en Marruecos',
    },
    description: {
      fr: "Configuration complète du Business Center TikTok et du pixel de conversion pour une marque e-commerce : création de 3 ensembles de publicités avec ciblage démographique précis (Casablanca, Rabat, Marrakech, Tanger, Fès), test de créatives A/B et paramétrage du budget pour minimiser le coût par commande COD.",
      ar: "إعداد حساب تيك توك للأعمال وتثبيت بيكسل التتبع لمتجر ملابس: إنشاء 3 مجموعات إعلانية مع استهداف دقيق للمدن المغربية الرئيسية والفئة العمرية 18-35 سنة، مع اختبار A/B للإعلانات لتقليل كلفة الطلب.",
      en: "Complete TikTok Business Center setup and conversion pixel installation for an e-commerce brand: 3 ad sets targeted to key Moroccan cities, A/B creative testing, and optimized budget allocation for COD conversions.",
      ru: "Настройка кабинета TikTok Ads и пикселя: создание 3 аудиторий с таргетом по городам, A/B тест креативов и оптимизация цены лида.",
      es: "Configuración de TikTok Business y pixel para tienda de moda: segmentación en ciudades clave de Marruecos y optimización de conversiones.",
    },
    priceDH: 300,
    turnaroundTime: '24h',
    city: 'Casablanca',
    completedDate: '2026-09-18',
    executor: {
      name: 'Soufiane D.',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
      role: {
        fr: 'Media Buyer & Expert TikTok Ads',
        ar: 'خبير إعلانات ممولة وتيك توك أدز',
        en: 'Media Buyer & TikTok Ads Pro',
        ru: 'Таргетолог TikTok Ads',
        es: 'Media Buyer y experto en TikTok Ads',
      },
      rating: 4.95,
      completedCount: 79,
      badge: {
        fr: 'Media Buyer Pro ⭐',
        ar: 'مسوق معتمد ⭐',
        en: 'Certified Media Buyer ⭐',
        ru: 'Профи рекламы ⭐',
        es: 'Media Buyer certificado ⭐',
      },
    },
    clientReview: {
      author: 'Marque Fashion (Casablanca)',
      rating: 5,
      comment: {
        fr: 'Dès le deuxième jour de campagne, nos commandes ont triplé avec un coût par achat très bas. Bravo !',
        ar: 'من ثاني يوم من إطلاق الحملة تضاعفت مبيعاتنا 3 مرات وبكلفة طلب منخفضة جداً. عمل احترافي!',
        en: 'From the second day of the campaign, our orders tripled with a very low CPA. Great job!',
        ru: 'Реклама сразу дала результат, пошли дешевые заявки и заказы. Очень грамотный таргетолог!',
        es: 'Desde el segundo día de campaña triplicamos los pedidos con un coste por compra muy bajo.',
      },
    },
    deliverables: ['Pixel TikTok configuré et testé', 'Campagne de conversion activée avec 3 ad sets', 'Rapport de paramétrage et recommandations'],
    tags: ['TikTok Ads', 'Pixel', 'Media Buying', 'Publicité', 'E-commerce'],
    searchIntentKeywords: ['tiktok ads', 'publicite tiktok', 'اعلانات تيك توك', 'اعلان ممول', 'pixel tiktok', 'media buyer', 'sponsorisation', 'e-commerce ads'],
  },
  {
    id: 1012,
    orderNumber: 2498112,
    category: 'copywriting',
    categoryLabel: {
      fr: 'Traduction & Rédaction',
      ar: 'ترجمة وكتابة محتوى',
      en: 'Translation & Copywriting',
      ru: 'Тексты и переводы',
      es: 'Traducción y redacción',
    },
    title: {
      fr: 'Correction orthographique, syntaxique et relecture complète d’un mémoire / rapport PFE de 35 pages',
      ar: 'تدقيق لغوي وإملائي شامل لتقرير تخرج أو مذكرة ماستر (35 صفحة بالفرنسية)',
      en: 'Complete grammar, spelling & syntax proofreading of a 35-page Master thesis / PFE report',
      ru: 'Вычитка, корректура и исправление ошибок в дипломной работе на 35 страниц',
      es: 'Corrección ortográfica y de estilo completa de memoria / tesis de 35 páginas',
    },
    description: {
      fr: "Relecture minutieuse et correction approfondie d'un rapport de fin d'études (PFE) de 35 pages en Français : élimination des fautes d'orthographe, grammaire, accords et ponctuation, amélioration de la clarté et du style académique, avec suivi des modifications sous Word et livraison d'une version finale propre en PDF.",
      ar: "مراجعة وتدقيق لغوي دقيق لبحث تخرج (PFE) يقع في 35 صفحة بالفرنسية: تصحيح الأخطاء النحوية والإملائية، تحسين الصياغة والأسلوب الأكاديمي، مع تسليم نسخة تتضمن التعديلات ونسخة نهائية منقحة بصيغة PDF.",
      en: "Thorough proofreading of a 35-page graduation report (PFE) in French: fixing spelling, grammar, punctuation, polishing academic phrasing, with Word track changes and clean PDF delivery.",
      ru: "Тщательная вычитка диплома на 35 страниц: исправление грамматики, пунктуации и стиля изложения с режимом отслеживания правок.",
      es: "Revisión minuciosa de memoria de grado de 35 páginas en Francés con control de cambios y entrega en PDF limpio.",
    },
    priceDH: 180,
    turnaroundTime: '24h',
    city: 'Rabat',
    completedDate: '2026-09-17',
    executor: {
      name: 'Youssef E.',
      avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=120&auto=format&fit=crop&q=80',
      role: {
        fr: 'Rédacteur & Correcteur Littéraire',
        ar: 'مدقق لغوي وكاتب أكاديمي',
        en: 'Editor & Academic Proofreader',
        ru: 'Корректор и редактор',
        es: 'Corrector de estilo y redactor',
      },
      rating: 4.93,
      completedCount: 115,
      badge: {
        fr: 'Plume Certifiée ⭐',
        ar: 'كاتب متميز ⭐',
        en: 'Certified Writer ⭐',
        ru: 'Топ копирайтер ⭐',
        es: 'Escritor certificado ⭐',
      },
    },
    clientReview: {
      author: 'Anas (Étudiant Master Rabat)',
      rating: 5,
      comment: {
        fr: 'Relecture impeccable qui a sauvé mon mémoire ! Les phrases sont beaucoup plus fluides. Merci infiniment !',
        ar: 'تدقيق ممتاز جداً أنقذ مذكرتي! الصياغة أصبحت سلسة واحترافية. شكراً جزيلاً لك أخي يوسف.',
        en: 'Flawless proofreading that polished my thesis! Phrasing is so much smoother now.',
        ru: 'Прекрасная вычитка! Исправил все мелкие ошибки и сделал текст читаемым. Спасибо огромное!',
        es: '¡Revisión impecable que mejoró mi tesis al 100%! Muy agradecido.',
      },
    },
    deliverables: ['Document Word avec suivi des modifications (Track Changes)', 'Version finale corrigée propre en Word et PDF'],
    tags: ['Correction', 'PFE', 'Mémoire', 'Français', 'Relecture', 'Orthographe'],
    searchIntentKeywords: ['correction pfe', 'relecture memoire', 'تدقيق لغوي', 'تصحيح فرنسية', 'fautes orthographe', 'memoire master', 'rapport de stage', 'proofreading'],
  },
  {
    id: 1013,
    orderNumber: 2498113,
    category: 'development',
    categoryLabel: {
      fr: 'Web & E-commerce',
      ar: 'برمجة ومتاجر إلكترونية',
      en: 'Web & E-commerce',
      ru: 'Разработка и IT',
      es: 'Desarrollo web y E-commerce',
    },
    title: {
      fr: 'Création d’une Landing Page monoproduit optimisée pour la conversion COD sur WordPress / Elementor',
      ar: 'تصميم وبرمجة صفحة هبوط لمنتج واحد (Landing Page) لزيادة المبيعات بالدفع عند الاستلام',
      en: 'Single-product high-converting COD Landing Page development on WordPress / Elementor',
      ru: 'Создание продающего одностраничника (Landing Page) с формой быстрого заказа',
      es: 'Creación de Landing Page monoproductora optimizada para conversión COD en WordPress / Elementor',
    },
    description: {
      fr: "Conception d'une page de vente ultra-rapide et responsive pour vendre un produit spécifique au Maroc : structure persuasive (accroche, bénéfices, avis clients, FAQ), formulaire de commande directe sans panier, compte à rebours d'urgence, et intégration du Pixel Facebook et TikTok.",
      ar: "تصميم صفحة هبوط احترافية وسريعة جداً متوافقة مع الهواتف: صياغة تسويقية مقنعة، نموذج طلب مباشر بدون المرور بالسلة، إدراج آراء المشترين، وربط بيكسل فيسبوك وتيك توك لتتبع التحويلات.",
      en: "Design of an ultra-fast, mobile-first sales landing page for a single product in Morocco: high-converting structure, direct 1-click order form, client testimonials, urgency timers, and Facebook/TikTok pixel tracking.",
      ru: "Разработка конверсионного лендинга для одного товара: форма быстрого заказа в один клик, таймер, отзывы и подключение пикселей.",
      es: "Diseño de landing page rápida para un producto con formulario directo, temporizador de urgencia y píxeles de seguimiento.",
    },
    priceDH: 450,
    turnaroundTime: '24h',
    city: 'En ligne',
    completedDate: '2026-09-16',
    executor: {
      name: 'Anass R.',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
      role: {
        fr: 'Expert Landing Pages & Conversion',
        ar: 'مختص صفحات هبوط وزيادة المبيعات',
        en: 'Landing Page & CRO Specialist',
        ru: 'Специалист по лендингам',
        es: 'Especialista en Landing Pages y CRO',
      },
      rating: 4.96,
      completedCount: 104,
      badge: {
        fr: 'Expert Web ⭐',
        ar: 'خبير برمجي ⭐',
        en: 'Web Expert ⭐',
        ru: 'Веб эксперт ⭐',
        es: 'Experto web ⭐',
      },
    },
    clientReview: {
      author: 'E-com Maroc (Tanger)',
      rating: 5,
      comment: {
        fr: 'Page ultra rapide, taux de conversion passé de 2% à 5.8% dès le premier jour de publicité. Super boulot !',
        ar: 'صفحة سريعة جداً ونسبة التحويل ارتفعت بشكل ملحوظ من أول يوم للإعلانات. عمل احترافي ومتقن!',
        en: 'Ultra fast landing page, our conversion rate jumped to 5.8% right away. Outstanding work!',
        ru: 'Лендинг получился очень быстрым, конверсия выросла в разы. Огромное спасибо!',
        es: 'Página súper rápida, la tasa de conversión subió al 5.8% desde el primer día.',
      },
    },
    deliverables: ['Landing page complète sur WordPress + Elementor', 'Formulaire de commande COD testé', 'Pixels TikTok & Meta connectés'],
    tags: ['Landing Page', 'WordPress', 'Elementor', 'COD', 'Conversion', 'Pixel'],
    searchIntentKeywords: ['landing page', 'صفحة هبوط', 'elementor', 'single product', 'monoproduit', 'page de vente', 'cro', 'creer landing page'],
  },
  {
    id: 1014,
    orderNumber: 2498114,
    category: 'assistance',
    categoryLabel: {
      fr: 'Saisie & Administratif',
      ar: 'إدخال بيانات وسكرتارية',
      en: 'Data Entry & Assistance',
      ru: 'Ввод данных и ассистент',
      es: 'Entrada de datos y asistencia',
    },
    title: {
      fr: 'Recherche web et collecte de 100 contacts B2B vérifiés (directeurs et gérants au Maroc)',
      ar: 'جمع وتدقيق بيانات 100 شركة ومدير مشتريات في المغرب (أرقام وإيميلات شغالة)',
      en: 'Web research & verified lead generation for 100 B2B business managers in Morocco',
      ru: 'Сбор базы из 100 проверенных контактов директоров и компаний в Марокко',
      es: 'Investigación web y recogida de 100 contactos B2B verificados de directores en Marruecos',
    },
    description: {
      fr: "Recherche ciblée et constitution d'un fichier Excel vérifié de 100 entreprises dans le secteur de l'agroalimentaire et cosmétique au Maroc : Nom de l'entreprise, Nom & Prénom du dirigeant, Poste exact, Ville, Numéro de téléphone direct vérifié (fixe/mobile), Adresse email professionnelle testée sans rebond et lien profil LinkedIn.",
      ar: "إنشاء قاعدة بيانات Excel مدققة تضم 100 شركة في قطاع الصناعات الغذائية والتجميلية بالمغرب. تتضمن لكل شركة: الاسم، اسم المسؤول، المنصب، المدينة، الهاتف المباشر، البريد الإلكتروني ورابط لينكد إن.",
      en: "Targeted research of 100 verified Moroccan business leads in food & beauty industries: Company Name, Decision Maker, Title, City, Valid Direct Phone, Bounce-free Email, and LinkedIn profile link.",
      ru: "Сбор базы из 100 компаний: название, ЛПР, должность, город, прямой телефон, проверенная почта и сайт.",
      es: "Elaboración de fichero Excel con 100 empresas verificadas en Marruecos: nombre, cargo, teléfono directo y email.",
    },
    priceDH: 200,
    turnaroundTime: '24h',
    city: 'Casablanca',
    completedDate: '2026-09-15',
    executor: {
      name: 'Kawtar B.',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
      role: {
        fr: 'Chercheuse de données & Lead Gen',
        ar: 'مختصة جمع وتدقيق البيانات',
        en: 'Data Researcher & Lead Gen',
        ru: 'Специалист по сбору данных',
        es: 'Investigadora de datos',
      },
      rating: 4.91,
      completedCount: 68,
      badge: {
        fr: 'Data Vérifiée ⭐',
        ar: 'بيانات موثوقة ⭐',
        en: 'Verified Data ⭐',
        ru: 'Проверенные данные ⭐',
        es: 'Datos verificados ⭐',
      },
    },
    clientReview: {
      author: 'Fournisseur Packaging (Casablanca)',
      rating: 5,
      comment: {
        fr: 'Excellente qualité de données, les numéros et adresses emails sont tous valides. Un gain de temps énorme pour notre équipe commerciale.',
        ar: 'بيانات دقيقة وعالية الجودة، وأرقام الهواتف والإيميلات كلها شغالة ومحدثة. وفرت علينا جهداً كبيراً.',
        en: 'Top data quality, all phone numbers and email addresses are valid. Huge time saver!',
        ru: 'База отличная, все контакты реальные и рабочие, без мусора. Очень помогли нашему отделу продаж!',
        es: 'Excelente calidad de datos, todos los teléfonos y correos son válidos.',
      },
    },
    deliverables: ['Tableau Excel .xlsx de 100 contacts B2B complets', 'Emails vérifiés avec taux de délivrabilité 100%'],
    tags: ['Leads', 'B2B', 'Prospection', 'Excel', 'LinkedIn', 'Contacts'],
    searchIntentKeywords: ['recherche contacts', 'leads b2b', 'جمع بيانات', 'داتا شركات', 'prospection maroc', 'fichiers clients', 'base de donnees', 'scrapping'],
  },
  {
    id: 1015,
    orderNumber: 2498115,
    category: 'micro',
    categoryLabel: {
      fr: 'Services terrain & Micro-tâches',
      ar: 'مهام ميدانية وخدمات سريعة',
      en: 'Field Errands & Micro-tasks',
      ru: 'Микро-задачи и поручения',
      es: 'Recados y microtareas',
    },
    title: {
      fr: 'Vérification sur place et reportage photo de 15 clichés d’un local commercial / appartement à Tanger',
      ar: 'معاينة ميدانية وتصوير 15 صورة واضحة لمحل تجاري أو شقة في طنجة',
      en: 'On-site inspection & 15 high-res photos of a commercial venue or apartment in Tangier',
      ru: 'Осмотр объекта и фотоотчет из 15 фото в Тانжере',
      es: 'Inspección presencial y reportaje de 15 fotos de local comercial o piso en Tánger',
    },
    description: {
      fr: "Déplacement sur place à Tanger (zone Malabata / Centre) pour vérifier l'état général d'un local / appartement : prise de 15 photos détaillées et nettes (façade, accès, pièces, installations d'eau et d'électricité, état des murs), vérification de la conformité de l'adresse et transmission par Google Drive sous 4 heures.",
      ar: "الانتقال إلى عين المكان بطنجة لمعاينة محل تجاري أو شقة مخصصة للكراء: التقاط 15 صورة واضحة ومضاءة جيداً (الواجهة، المدخل، العداد، السقف) وإرسالها مباشرة مع تقرير موجز عن حالة المحل.",
      en: "On-site visit in Tangier to inspect the general condition of a commercial unit / apartment for rent: 15 sharp photos taken (facade, entrance, meter, interior condition) and shared via Google Drive within 4 hours.",
      ru: "Выезд на объект в Танжере: проверка состояния помещения, 15 качественных фото фасада и интерьера, отправка отчета в тот же день.",
      es: "Visita presencial a inmueble en Tánger: comprobación del estado general, 15 fotos detalladas y envío rápido por Drive.",
    },
    priceDH: 180,
    turnaroundTime: '6h',
    city: 'Tanger',
    completedDate: '2026-09-14',
    executor: {
      name: 'Ilyas H.',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=120&auto=format&fit=crop&q=80',
      role: {
        fr: 'Agent de terrain & Auditeur Local',
        ar: 'مفتش ميداني ومصور',
        en: 'Field Inspector & Auditor',
        ru: 'Локальный агент',
        es: 'Agente de campo e inspector',
      },
      rating: 4.89,
      completedCount: 46,
      badge: {
        fr: 'Agent Tanger ⭐',
        ar: 'معتمد طنجة ⭐',
        en: 'Tangier Agent ⭐',
        ru: 'Агент в Танжере ⭐',
        es: 'Agente Tánger ⭐',
      },
    },
    clientReview: {
      author: 'Investisseur Immobilier (Paris)',
      rating: 5,
      comment: {
        fr: 'Depuis la France, ce service est une bénédiction. Photos de qualité reçues dans l’après-midi. Merci Ilyas !',
        ar: 'خدمة ممتازة ومريحة جداً ونحن متواجدون بالخارج. صور واضحة وتفاصيل دقيقة. شكراً إلياس!',
        en: 'Being abroad, this service is a lifesaver. High quality photos delivered in the afternoon.',
        ru: 'Очень выручил! Находясь в другом городе, получил подробный фотоотчет за несколько часов.',
        es: 'Estando fuera, este servicio es una bendición. Fotos nítidas y reporte rápido.',
      },
    },
    deliverables: ['Album Google Drive de 15 photos HD géolocalisées et datées', 'Rapport bref de constatation'],
    tags: ['Tanger', 'Visite terrain', 'Photos', 'Immobilier', 'Vérification'],
    searchIntentKeywords: ['visite tanger', 'photos immobilier', 'معاينة عقار', 'طنجة', 'inspection appartement', 'photos local', 'visite sur place', 'mission terrain'],
  },
  {
    id: 1016,
    orderNumber: 2498116,
    category: 'copywriting',
    categoryLabel: {
      fr: 'Traduction & Rédaction',
      ar: 'ترجمة وكتابة محتوى',
      en: 'Translation & Copywriting',
      ru: 'Тексты и переводы',
      es: 'Traducción y redacción',
    },
    title: {
      fr: 'Rédaction de 10 fiches produits e-commerce vendeuses avec structure SEO et mots-clés en Darija et Français',
      ar: 'كتابة 10 بطاقات وصف منتج تسويقية متوافقة مع السيو بالدارجة والفرنسية',
      en: 'Copywriting 10 high-converting e-commerce product pages with SEO keywords in Darija & French',
      ru: 'Написание 10 продающих карточек товаров с SEO-оптимизацией',
      es: 'Redacción de 10 fichas de producto e-commerce persuasivas con SEO en Darija y Francés',
    },
    description: {
      fr: "Rédaction persuasive pour 10 fiches produits d'une boutique en ligne (vêtements, accessoires ou cosmétiques) : titre accrocheur, paragraphe descriptif émotionnel, 5 bénéfices clés à puces, spécifications techniques, balises méta-titre et méta-description pour le référencement Google.",
      ar: "كتابة نصوص تسويقية مقنعة لـ 10 منتجات لمتجر إلكتروني: عنوان جذاب، وصف عاطفي للمنتج، 5 فوائد رئيسية، نقاط الاستخدام، وتجهيز الكلمات المفتاحية والوصف للسيو.",
      en: "Persuasive copywriting for 10 online store product pages: compelling hook, storytelling description, 5 bullet-point benefits, specs, and SEO meta tags.",
      ru: "Создание 10 продающих карточек товаров: цепляющий заголовок, описание преимуществ, характеристики и мета-теги для поиска.",
      es: "Redacción de 10 fichas de producto con estructura persuasiva y etiquetas meta SEO para Google.",
    },
    priceDH: 160,
    turnaroundTime: '24h',
    city: 'Marrakech',
    completedDate: '2026-09-12',
    executor: {
      name: 'Chaimae S.',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
      role: {
        fr: 'Rédactrice E-commerce & Storytelling',
        ar: 'كاتبة محتوى تسويقي وقصصي',
        en: 'E-commerce & Storytelling Copywriter',
        ru: 'Копирайтер для маркетплейсов',
        es: 'Redactora de e-commerce y storytelling',
      },
      rating: 4.97,
      completedCount: 84,
      badge: {
        fr: 'Plume E-com ⭐',
        ar: 'مبدعة إعلانات ⭐',
        en: 'E-com Writer ⭐',
        ru: 'Топ автор карточек ⭐',
        es: 'Escritora E-com ⭐',
      },
    },
    clientReview: {
      author: 'Bio Natur Maroc (Marrakech)',
      rating: 5,
      comment: {
        fr: 'Textes percutants qui mettent vraiment en valeur nos produits artisanaux. Très belle écriture.',
        ar: 'نصوص تسويقية رائعة تبرز أصالة وقيمة منتجاتنا الطبيعية بأسلوب يجذب الزبائن.',
        en: 'Compelling texts that highlight our artisan products value. Beautiful writing!',
        ru: 'Описания получились сочными и живыми, конверсия в заказы заметно выросла!',
        es: 'Textos muy persuasivos que destacan el valor artesanal de nuestros productos.',
      },
    },
    deliverables: ['Tableau Word / Excel structuré avec les 10 fiches', 'Méta-titres et méta-descriptions SEO inclus'],
    tags: ['Fiches produits', 'E-commerce', 'Cosmétique', 'Darija', 'SEO'],
    searchIntentKeywords: ['fiches produits', 'redaction seo', 'وصف منتجات', 'كتابة محتوى', 'copywriting e-commerce', 'descriptions produits', 'textes de vente', 'articles seo'],
  },
];
